/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Context associated with Qna.
 *
 */
class ContextDTO {
  /**
   * Create a ContextDTO.
   * @property {boolean} [isContextOnly] To mark if a prompt is relevant only
   * with a previous question or not.
   * true - Do not include this QnA as search result for queries without
   * context
   * false - ignores context and includes this QnA in search result
   * @property {array} [prompts] List of prompts associated with the answer.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ContextDTO
   *
   * @returns {object} metadata of ContextDTO
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ContextDTO',
      type: {
        name: 'Composite',
        className: 'ContextDTO',
        modelProperties: {
          isContextOnly: {
            required: false,
            serializedName: 'isContextOnly',
            type: {
              name: 'Boolean'
            }
          },
          prompts: {
            required: false,
            serializedName: 'prompts',
            constraints: {
              MaxItems: 20
            },
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'PromptDTOElementType',
                  type: {
                    name: 'Composite',
                    className: 'PromptDTO'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = ContextDTO;
