/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Endpoint settings.
 *
 */
class EndpointSettingsDTO {
  /**
   * Create a EndpointSettingsDTO.
   * @property {object} [activeLearning] Active Learning settings of the
   * endpoint.
   */
  constructor() {
  }

  /**
   * Defines the metadata of EndpointSettingsDTO
   *
   * @returns {object} metadata of EndpointSettingsDTO
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'EndpointSettingsDTO',
      type: {
        name: 'Composite',
        className: 'EndpointSettingsDTO',
        modelProperties: {
          activeLearning: {
            required: false,
            serializedName: 'activeLearning',
            type: {
              name: 'Composite',
              className: 'EndpointSettingsDTOActiveLearning'
            }
          }
        }
      }
    };
  }
}

module.exports = EndpointSettingsDTO;
