/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Gets the application HTTP endpoints.
 *
 */
class ApplicationGetHttpsEndpoint {
  /**
   * Create a ApplicationGetHttpsEndpoint.
   * @property {array} [accessModes] The list of access modes for the
   * application.
   * @property {string} [location] The location of the endpoint.
   * @property {number} [destinationPort] The destination port to connect to.
   * @property {number} [publicPort] The public port to connect to.
   * @property {string} [subDomainSuffix] The subDomainSuffix of the
   * application and can not greater than 3 characters.
   * @property {boolean} [disableGatewayAuth] The value indicates whether to
   * disable GatewayAuth.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ApplicationGetHttpsEndpoint
   *
   * @returns {object} metadata of ApplicationGetHttpsEndpoint
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ApplicationGetHttpsEndpoint',
      type: {
        name: 'Composite',
        className: 'ApplicationGetHttpsEndpoint',
        modelProperties: {
          accessModes: {
            required: false,
            serializedName: 'accessModes',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          location: {
            required: false,
            serializedName: 'location',
            type: {
              name: 'String'
            }
          },
          destinationPort: {
            required: false,
            serializedName: 'destinationPort',
            type: {
              name: 'Number'
            }
          },
          publicPort: {
            required: false,
            serializedName: 'publicPort',
            type: {
              name: 'Number'
            }
          },
          subDomainSuffix: {
            required: false,
            serializedName: 'subDomainSuffix',
            type: {
              name: 'String'
            }
          },
          disableGatewayAuth: {
            required: false,
            serializedName: 'disableGatewayAuth',
            type: {
              name: 'Boolean'
            }
          }
        }
      }
    };
  }
}

module.exports = ApplicationGetHttpsEndpoint;
