/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Analyze API call result.
 *
 */
class AnalyzeResult {
  /**
   * Create a AnalyzeResult.
   * @property {string} [status] Status of the analyze operation. Possible
   * values include: 'success', 'partialSuccess', 'failure'
   * @property {array} [pages] Page level information extracted in the analyzed
   * document.
   * @property {array} [errors] List of errors reported during the analyze
   * operation.
   */
  constructor() {
  }

  /**
   * Defines the metadata of AnalyzeResult
   *
   * @returns {object} metadata of AnalyzeResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'AnalyzeResult',
      type: {
        name: 'Composite',
        className: 'AnalyzeResult',
        modelProperties: {
          status: {
            required: false,
            serializedName: 'status',
            type: {
              name: 'String'
            }
          },
          pages: {
            required: false,
            serializedName: 'pages',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ExtractedPageElementType',
                  type: {
                    name: 'Composite',
                    className: 'ExtractedPage'
                  }
              }
            }
          },
          errors: {
            required: false,
            serializedName: 'errors',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'FormOperationErrorElementType',
                  type: {
                    name: 'Composite',
                    className: 'FormOperationError'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = AnalyzeResult;
