/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Reference to an OCR word.
 *
 */
class ElementReference {
  /**
   * Create a ElementReference.
   * @property {string} [ref]
   */
  constructor() {
  }

  /**
   * Defines the metadata of ElementReference
   *
   * @returns {object} metadata of ElementReference
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'elementReference',
      type: {
        name: 'Composite',
        className: 'ElementReference',
        modelProperties: {
          ref: {
            required: false,
            serializedName: '$ref',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ElementReference;
