/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Representation of a key-value pair as a list
 * of key and value tokens.
 *
 */
class ExtractedKeyValuePair {
  /**
   * Create a ExtractedKeyValuePair.
   * @property {array} [key] List of tokens for the extracted key in a
   * key-value pair.
   * @property {array} [value] List of tokens for the extracted value in a
   * key-value pair.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ExtractedKeyValuePair
   *
   * @returns {object} metadata of ExtractedKeyValuePair
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ExtractedKeyValuePair',
      type: {
        name: 'Composite',
        className: 'ExtractedKeyValuePair',
        modelProperties: {
          key: {
            required: false,
            serializedName: 'key',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ExtractedTokenElementType',
                  type: {
                    name: 'Composite',
                    className: 'ExtractedToken'
                  }
              }
            }
          },
          value: {
            required: false,
            serializedName: 'value',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ExtractedTokenElementType',
                  type: {
                    name: 'Composite',
                    className: 'ExtractedToken'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = ExtractedKeyValuePair;
