/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Extraction information of a single page in a
 * with a document.
 *
 */
class ExtractedPage {
  /**
   * Create a ExtractedPage.
   * @property {number} [number] Page number.
   * @property {number} [height] Height of the page (in pixels).
   * @property {number} [width] Width of the page (in pixels).
   * @property {number} [clusterId] Cluster identifier.
   * @property {array} [keyValuePairs] List of Key-Value pairs extracted from
   * the page.
   * @property {array} [tables] List of Tables and their information extracted
   * from the page.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ExtractedPage
   *
   * @returns {object} metadata of ExtractedPage
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ExtractedPage',
      type: {
        name: 'Composite',
        className: 'ExtractedPage',
        modelProperties: {
          number: {
            required: false,
            serializedName: 'number',
            type: {
              name: 'Number'
            }
          },
          height: {
            required: false,
            serializedName: 'height',
            type: {
              name: 'Number'
            }
          },
          width: {
            required: false,
            serializedName: 'width',
            type: {
              name: 'Number'
            }
          },
          clusterId: {
            required: false,
            serializedName: 'clusterId',
            type: {
              name: 'Number'
            }
          },
          keyValuePairs: {
            required: false,
            serializedName: 'keyValuePairs',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ExtractedKeyValuePairElementType',
                  type: {
                    name: 'Composite',
                    className: 'ExtractedKeyValuePair'
                  }
              }
            }
          },
          tables: {
            required: false,
            serializedName: 'tables',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ExtractedTableElementType',
                  type: {
                    name: 'Composite',
                    className: 'ExtractedTable'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = ExtractedPage;
