/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

exports.TrainRequest = require('./trainRequest');
exports.FormDocumentReport = require('./formDocumentReport');
exports.FormOperationError = require('./formOperationError');
exports.TrainResult = require('./trainResult');
exports.KeysResult = require('./keysResult');
exports.ModelResult = require('./modelResult');
exports.ModelsResult = require('./modelsResult');
exports.InnerError = require('./innerError');
exports.ErrorInformation = require('./errorInformation');
exports.ErrorResponse = require('./errorResponse');
exports.ExtractedToken = require('./extractedToken');
exports.ExtractedKeyValuePair = require('./extractedKeyValuePair');
exports.ExtractedTableColumn = require('./extractedTableColumn');
exports.ExtractedTable = require('./extractedTable');
exports.ExtractedPage = require('./extractedPage');
exports.AnalyzeResult = require('./analyzeResult');
exports.Word = require('./word');
exports.Line = require('./line');
exports.TextRecognitionResult = require('./textRecognitionResult');
exports.ElementReference = require('./elementReference');
exports.FieldValue = require('./fieldValue');
exports.UnderstandingResult = require('./understandingResult');
exports.ReadReceiptResult = require('./readReceiptResult');
exports.StringValue = require('./stringValue');
exports.NumberValue = require('./numberValue');
exports.ComputerVisionError = require('./computerVisionError');
exports.ImageUrl = require('./imageUrl');
exports.discriminators = {
  'fieldValue' : exports.FieldValue,
  'FieldValue.stringValue' : exports.StringValue,
  'FieldValue.numberValue' : exports.NumberValue
};
