/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Result of an operation to get
 * the keys extracted by a model.
 *
 */
class KeysResult {
  /**
   * Create a KeysResult.
   * @property {object} [clusters] Object mapping ClusterIds to Key lists.
   */
  constructor() {
  }

  /**
   * Defines the metadata of KeysResult
   *
   * @returns {object} metadata of KeysResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'KeysResult',
      type: {
        name: 'Composite',
        className: 'KeysResult',
        modelProperties: {
          clusters: {
            required: false,
            serializedName: 'clusters',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'ArrayElementType',
                  type: {
                    name: 'Sequence',
                    element: {
                        required: false,
                        serializedName: 'StringElementType',
                        type: {
                          name: 'String'
                        }
                    }
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = KeysResult;
