/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Contract to initiate a train request.
 *
 */
class TrainRequest {
  /**
   * Create a TrainRequest.
   * @property {string} source Get or set source path.
   */
  constructor() {
  }

  /**
   * Defines the metadata of TrainRequest
   *
   * @returns {object} metadata of TrainRequest
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'TrainRequest',
      type: {
        name: 'Composite',
        className: 'TrainRequest',
        modelProperties: {
          source: {
            required: true,
            serializedName: 'source',
            constraints: {
              MaxLength: 2048,
              MinLength: 0
            },
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = TrainRequest;
