/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Attachments.
 */
class Attachments {
  /**
   * Create a Attachments.
   * @property {uuid} [parentId] The parentId property for the attachments
   * entity
   * @property {uuid} [id] The id property for the attachments entity
   * @property {string} [fileName] The fileName property for the attachments
   * entity
   * @property {number} [byteSize] The byteSize property for the attachments
   * entity
   * @property {string} [content] The content property for the attachments
   * entity
   * @property {date} [lastModifiedDateTime] The lastModifiedDateTime property
   * for the attachments entity
   */
  constructor() {
  }

  /**
   * Defines the metadata of Attachments
   *
   * @returns {object} metadata of Attachments
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'attachments',
      type: {
        name: 'Composite',
        className: 'Attachments',
        modelProperties: {
          parentId: {
            required: false,
            serializedName: 'parentId',
            type: {
              name: 'String'
            }
          },
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          fileName: {
            required: false,
            serializedName: 'fileName',
            constraints: {
              MaxLength: 250
            },
            type: {
              name: 'String'
            }
          },
          byteSize: {
            required: false,
            serializedName: 'byteSize',
            type: {
              name: 'Number'
            }
          },
          content: {
            required: false,
            serializedName: 'content',
            type: {
              name: 'String'
            }
          },
          lastModifiedDateTime: {
            required: false,
            serializedName: 'lastModifiedDateTime',
            type: {
              name: 'DateTime'
            }
          }
        }
      }
    };
  }
}

module.exports = Attachments;
