/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a BodyModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel.
 */
class BodyModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel {
  /**
   * Create a BodyModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel.
   * @property {uuid} [id] The id property for the timeRegistrationEntry entity
   * @property {uuid} [employeeId] The employeeId property for the
   * timeRegistrationEntry entity
   * @property {string} [employeeNumber] The employeeNumber property for the
   * timeRegistrationEntry entity
   * @property {number} [lineNumber] The lineNumber property for the
   * timeRegistrationEntry entity
   * @property {date} [date] The date property for the timeRegistrationEntry
   * entity
   * @property {number} [quantity] The quantity property for the
   * timeRegistrationEntry entity
   * @property {string} [status] The status property for the
   * timeRegistrationEntry entity
   * @property {uuid} [unitOfMeasureId] The unitOfMeasureId property for the
   * timeRegistrationEntry entity
   * @property {object} [unitOfMeasure]
   * @property {string} [unitOfMeasure.code] The code property for the
   * unitofmeasuretype entity
   * @property {string} [unitOfMeasure.displayName] The displayName property
   * for the unitofmeasuretype entity
   * @property {string} [unitOfMeasure.symbol] The symbol property for the
   * unitofmeasuretype entity
   * @property {object} [unitOfMeasure.unitConversion]
   * @property {string} [unitOfMeasure.unitConversion.toUnitOfMeasure] The
   * toUnitOfMeasure property for the itemunitofmeasureconversiontype entity
   * @property {number} [unitOfMeasure.unitConversion.fromToConversionRate] The
   * fromToConversionRate property for the itemunitofmeasureconversiontype
   * entity
   * @property {array} [unitOfMeasure.unitConversion.picture]
   * @property {array} [unitOfMeasure.unitConversion.defaultDimensions]
   * @property {object} [unitOfMeasure.unitConversion.itemCategory]
   * @property {uuid} [unitOfMeasure.unitConversion.itemCategory.id] The id
   * property for the itemCategory entity
   * @property {string} [unitOfMeasure.unitConversion.itemCategory.code] The
   * code property for the itemCategory entity
   * @property {string} [unitOfMeasure.unitConversion.itemCategory.displayName]
   * The displayName property for the itemCategory entity
   * @property {date}
   * [unitOfMeasure.unitConversion.itemCategory.lastModifiedDateTime] The
   * lastModifiedDateTime property for the itemCategory entity
   * @property {array} [unitOfMeasure.picture]
   * @property {array} [unitOfMeasure.defaultDimensions]
   * @property {object} [unitOfMeasure.itemCategory]
   * @property {uuid} [unitOfMeasure.itemCategory.id] The id property for the
   * itemCategory entity
   * @property {string} [unitOfMeasure.itemCategory.code] The code property for
   * the itemCategory entity
   * @property {string} [unitOfMeasure.itemCategory.displayName] The
   * displayName property for the itemCategory entity
   * @property {date} [unitOfMeasure.itemCategory.lastModifiedDateTime] The
   * lastModifiedDateTime property for the itemCategory entity
   * @property {date} [lastModfiedDateTime] The lastModfiedDateTime property
   * for the timeRegistrationEntry entity
   */
  constructor() {
  }

  /**
   * Defines the metadata of BodyModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel
   *
   * @returns {object} metadata of BodyModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'body',
      type: {
        name: 'Composite',
        className: 'BodyModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          employeeId: {
            required: false,
            serializedName: 'employeeId',
            type: {
              name: 'String'
            }
          },
          employeeNumber: {
            required: false,
            serializedName: 'employeeNumber',
            constraints: {
              MaxLength: 20
            },
            type: {
              name: 'String'
            }
          },
          lineNumber: {
            required: false,
            serializedName: 'lineNumber',
            type: {
              name: 'Number'
            }
          },
          date: {
            required: false,
            serializedName: 'date',
            type: {
              name: 'DateTime'
            }
          },
          quantity: {
            required: false,
            serializedName: 'quantity',
            type: {
              name: 'Number'
            }
          },
          status: {
            required: false,
            serializedName: 'status',
            type: {
              name: 'String'
            }
          },
          unitOfMeasureId: {
            required: false,
            serializedName: 'unitOfMeasureId',
            type: {
              name: 'String'
            }
          },
          unitOfMeasure: {
            required: false,
            serializedName: 'unitOfMeasure',
            type: {
              name: 'Composite',
              className: 'Unitofmeasuretype'
            }
          },
          lastModfiedDateTime: {
            required: false,
            serializedName: 'lastModfiedDateTime',
            type: {
              name: 'DateTime'
            }
          }
        }
      }
    };
  }
}

module.exports = BodyModelModelModelModelModelModelModelModelModelModelModelModelModelModelModel;
