/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a BodyModelModelModelModelModelModelModelModel.
 */
class BodyModelModelModelModelModelModelModelModel {
  /**
   * Create a BodyModelModelModelModelModelModelModelModel.
   * @property {uuid} [id] The id property for the customerPaymentJournal
   * entity
   * @property {string} [code] The code property for the customerPaymentJournal
   * entity
   * @property {string} [displayName] The displayName property for the
   * customerPaymentJournal entity
   * @property {date} [lastModifiedDateTime] The lastModifiedDateTime property
   * for the customerPaymentJournal entity
   * @property {uuid} [balancingAccountId] The balancingAccountId property for
   * the customerPaymentJournal entity
   * @property {string} [balancingAccountNumber] The balancingAccountNumber
   * property for the customerPaymentJournal entity
   */
  constructor() {
  }

  /**
   * Defines the metadata of BodyModelModelModelModelModelModelModelModel
   *
   * @returns {object} metadata of BodyModelModelModelModelModelModelModelModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'body',
      type: {
        name: 'Composite',
        className: 'BodyModelModelModelModelModelModelModelModel',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          code: {
            required: false,
            serializedName: 'code',
            constraints: {
              MaxLength: 10
            },
            type: {
              name: 'String'
            }
          },
          displayName: {
            required: false,
            serializedName: 'displayName',
            constraints: {
              MaxLength: 100
            },
            type: {
              name: 'String'
            }
          },
          lastModifiedDateTime: {
            required: false,
            serializedName: 'lastModifiedDateTime',
            type: {
              name: 'DateTime'
            }
          },
          balancingAccountId: {
            required: false,
            serializedName: 'balancingAccountId',
            type: {
              name: 'String'
            }
          },
          balancingAccountNumber: {
            required: false,
            serializedName: 'balancingAccountNumber',
            constraints: {
              MaxLength: 20
            },
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = BodyModelModelModelModelModelModelModelModel;
