/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Company.
 */
class Company {
  /**
   * Create a Company.
   * @property {uuid} [id] The id property for the company entity
   * @property {string} [systemVersion] The systemVersion property for the
   * company entity
   * @property {string} [name] The name property for the company entity
   * @property {string} [displayName] The displayName property for the company
   * entity
   * @property {string} [businessProfileId] The businessProfileId property for
   * the company entity
   * @property {array} [items]
   * @property {array} [picture]
   * @property {array} [defaultDimensions]
   * @property {array} [customers]
   * @property {array} [customerFinancialDetails]
   * @property {array} [vendors]
   * @property {array} [companyInformation]
   * @property {array} [salesInvoices]
   * @property {array} [salesInvoiceLines]
   * @property {array} [pdfDocument]
   * @property {array} [customerPaymentJournals]
   * @property {array} [customerPayments]
   * @property {array} [accounts]
   * @property {array} [taxGroups]
   * @property {array} [journals]
   * @property {array} [journalLines]
   * @property {array} [attachments]
   * @property {array} [employees]
   * @property {array} [timeRegistrationEntries]
   * @property {array} [generalLedgerEntries]
   * @property {array} [currencies]
   * @property {array} [paymentMethods]
   * @property {array} [dimensions]
   * @property {array} [dimensionValues]
   * @property {array} [dimensionLines]
   * @property {array} [paymentTerms]
   * @property {array} [shipmentMethods]
   * @property {array} [itemCategories]
   * @property {array} [cashFlowStatement]
   * @property {array} [countriesRegions]
   * @property {array} [salesOrders]
   * @property {array} [salesOrderLines]
   * @property {array} [retainedEarningsStatement]
   * @property {array} [unitsOfMeasure]
   * @property {array} [agedAccountsReceivable]
   * @property {array} [agedAccountsPayable]
   * @property {array} [balanceSheet]
   * @property {array} [trialBalance]
   * @property {array} [incomeStatement]
   * @property {array} [taxAreas]
   * @property {array} [salesQuotes]
   * @property {array} [salesQuoteLines]
   * @property {array} [salesCreditMemos]
   * @property {array} [salesCreditMemoLines]
   * @property {array} [generalLedgerEntryAttachments]
   * @property {array} [purchaseInvoices]
   * @property {array} [purchaseInvoiceLines]
   * @property {array} [customerSales]
   * @property {array} [vendorPurchases]
   */
  constructor() {
  }

  /**
   * Defines the metadata of Company
   *
   * @returns {object} metadata of Company
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'company',
      type: {
        name: 'Composite',
        className: 'Company',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          systemVersion: {
            required: false,
            serializedName: 'systemVersion',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            constraints: {
              MaxLength: 30
            },
            type: {
              name: 'String'
            }
          },
          displayName: {
            required: false,
            serializedName: 'displayName',
            constraints: {
              MaxLength: 250
            },
            type: {
              name: 'String'
            }
          },
          businessProfileId: {
            required: false,
            serializedName: 'businessProfileId',
            constraints: {
              MaxLength: 250
            },
            type: {
              name: 'String'
            }
          },
          items: {
            required: false,
            serializedName: 'items',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ItemElementType',
                  type: {
                    name: 'Composite',
                    className: 'Item'
                  }
              }
            }
          },
          picture: {
            required: false,
            serializedName: 'picture',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'PictureElementType',
                  type: {
                    name: 'Composite',
                    className: 'Picture'
                  }
              }
            }
          },
          defaultDimensions: {
            required: false,
            serializedName: 'defaultDimensions',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'DefaultDimensionsElementType',
                  type: {
                    name: 'Composite',
                    className: 'DefaultDimensions'
                  }
              }
            }
          },
          customers: {
            required: false,
            serializedName: 'customers',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CustomerElementType',
                  type: {
                    name: 'Composite',
                    className: 'Customer'
                  }
              }
            }
          },
          customerFinancialDetails: {
            required: false,
            serializedName: 'customerFinancialDetails',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CustomerFinancialDetailElementType',
                  type: {
                    name: 'Composite',
                    className: 'CustomerFinancialDetail'
                  }
              }
            }
          },
          vendors: {
            required: false,
            serializedName: 'vendors',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'VendorElementType',
                  type: {
                    name: 'Composite',
                    className: 'Vendor'
                  }
              }
            }
          },
          companyInformation: {
            required: false,
            serializedName: 'companyInformation',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CompanyInformationElementType',
                  type: {
                    name: 'Composite',
                    className: 'CompanyInformation'
                  }
              }
            }
          },
          salesInvoices: {
            required: false,
            serializedName: 'salesInvoices',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'SalesInvoiceElementType',
                  type: {
                    name: 'Composite',
                    className: 'SalesInvoice'
                  }
              }
            }
          },
          salesInvoiceLines: {
            required: false,
            serializedName: 'salesInvoiceLines',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'SalesInvoiceLineElementType',
                  type: {
                    name: 'Composite',
                    className: 'SalesInvoiceLine'
                  }
              }
            }
          },
          pdfDocument: {
            required: false,
            serializedName: 'pdfDocument',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'PdfDocumentElementType',
                  type: {
                    name: 'Composite',
                    className: 'PdfDocument'
                  }
              }
            }
          },
          customerPaymentJournals: {
            required: false,
            serializedName: 'customerPaymentJournals',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CustomerPaymentJournalElementType',
                  type: {
                    name: 'Composite',
                    className: 'CustomerPaymentJournal'
                  }
              }
            }
          },
          customerPayments: {
            required: false,
            serializedName: 'customerPayments',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CustomerPaymentElementType',
                  type: {
                    name: 'Composite',
                    className: 'CustomerPayment'
                  }
              }
            }
          },
          accounts: {
            required: false,
            serializedName: 'accounts',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'AccountElementType',
                  type: {
                    name: 'Composite',
                    className: 'Account'
                  }
              }
            }
          },
          taxGroups: {
            required: false,
            serializedName: 'taxGroups',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'TaxGroupElementType',
                  type: {
                    name: 'Composite',
                    className: 'TaxGroup'
                  }
              }
            }
          },
          journals: {
            required: false,
            serializedName: 'journals',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'JournalElementType',
                  type: {
                    name: 'Composite',
                    className: 'Journal'
                  }
              }
            }
          },
          journalLines: {
            required: false,
            serializedName: 'journalLines',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'JournalLineElementType',
                  type: {
                    name: 'Composite',
                    className: 'JournalLine'
                  }
              }
            }
          },
          attachments: {
            required: false,
            serializedName: 'attachments',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'AttachmentsElementType',
                  type: {
                    name: 'Composite',
                    className: 'Attachments'
                  }
              }
            }
          },
          employees: {
            required: false,
            serializedName: 'employees',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'EmployeeElementType',
                  type: {
                    name: 'Composite',
                    className: 'Employee'
                  }
              }
            }
          },
          timeRegistrationEntries: {
            required: false,
            serializedName: 'timeRegistrationEntries',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'TimeRegistrationEntryElementType',
                  type: {
                    name: 'Composite',
                    className: 'TimeRegistrationEntry'
                  }
              }
            }
          },
          generalLedgerEntries: {
            required: false,
            serializedName: 'generalLedgerEntries',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'GeneralLedgerEntryElementType',
                  type: {
                    name: 'Composite',
                    className: 'GeneralLedgerEntry'
                  }
              }
            }
          },
          currencies: {
            required: false,
            serializedName: 'currencies',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CurrencyElementType',
                  type: {
                    name: 'Composite',
                    className: 'Currency'
                  }
              }
            }
          },
          paymentMethods: {
            required: false,
            serializedName: 'paymentMethods',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'PaymentMethodElementType',
                  type: {
                    name: 'Composite',
                    className: 'PaymentMethod'
                  }
              }
            }
          },
          dimensions: {
            required: false,
            serializedName: 'dimensions',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'DimensionElementType',
                  type: {
                    name: 'Composite',
                    className: 'Dimension'
                  }
              }
            }
          },
          dimensionValues: {
            required: false,
            serializedName: 'dimensionValues',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'DimensionValueElementType',
                  type: {
                    name: 'Composite',
                    className: 'DimensionValue'
                  }
              }
            }
          },
          dimensionLines: {
            required: false,
            serializedName: 'dimensionLines',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'DimensionLineElementType',
                  type: {
                    name: 'Composite',
                    className: 'DimensionLine'
                  }
              }
            }
          },
          paymentTerms: {
            required: false,
            serializedName: 'paymentTerms',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'PaymentTermElementType',
                  type: {
                    name: 'Composite',
                    className: 'PaymentTerm'
                  }
              }
            }
          },
          shipmentMethods: {
            required: false,
            serializedName: 'shipmentMethods',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ShipmentMethodElementType',
                  type: {
                    name: 'Composite',
                    className: 'ShipmentMethod'
                  }
              }
            }
          },
          itemCategories: {
            required: false,
            serializedName: 'itemCategories',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ItemCategoryElementType',
                  type: {
                    name: 'Composite',
                    className: 'ItemCategory'
                  }
              }
            }
          },
          cashFlowStatement: {
            required: false,
            serializedName: 'cashFlowStatement',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CashFlowStatementElementType',
                  type: {
                    name: 'Composite',
                    className: 'CashFlowStatement'
                  }
              }
            }
          },
          countriesRegions: {
            required: false,
            serializedName: 'countriesRegions',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CountryRegionElementType',
                  type: {
                    name: 'Composite',
                    className: 'CountryRegion'
                  }
              }
            }
          },
          salesOrders: {
            required: false,
            serializedName: 'salesOrders',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'SalesOrderElementType',
                  type: {
                    name: 'Composite',
                    className: 'SalesOrder'
                  }
              }
            }
          },
          salesOrderLines: {
            required: false,
            serializedName: 'salesOrderLines',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'SalesOrderLineElementType',
                  type: {
                    name: 'Composite',
                    className: 'SalesOrderLine'
                  }
              }
            }
          },
          retainedEarningsStatement: {
            required: false,
            serializedName: 'retainedEarningsStatement',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'RetainedEarningsStatementElementType',
                  type: {
                    name: 'Composite',
                    className: 'RetainedEarningsStatement'
                  }
              }
            }
          },
          unitsOfMeasure: {
            required: false,
            serializedName: 'unitsOfMeasure',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'UnitOfMeasureElementType',
                  type: {
                    name: 'Composite',
                    className: 'UnitOfMeasure'
                  }
              }
            }
          },
          agedAccountsReceivable: {
            required: false,
            serializedName: 'agedAccountsReceivable',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'AgedAccountsReceivableElementType',
                  type: {
                    name: 'Composite',
                    className: 'AgedAccountsReceivable'
                  }
              }
            }
          },
          agedAccountsPayable: {
            required: false,
            serializedName: 'agedAccountsPayable',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'AgedAccountsPayableElementType',
                  type: {
                    name: 'Composite',
                    className: 'AgedAccountsPayable'
                  }
              }
            }
          },
          balanceSheet: {
            required: false,
            serializedName: 'balanceSheet',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'BalanceSheetElementType',
                  type: {
                    name: 'Composite',
                    className: 'BalanceSheet'
                  }
              }
            }
          },
          trialBalance: {
            required: false,
            serializedName: 'trialBalance',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'TrialBalanceElementType',
                  type: {
                    name: 'Composite',
                    className: 'TrialBalance'
                  }
              }
            }
          },
          incomeStatement: {
            required: false,
            serializedName: 'incomeStatement',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'IncomeStatementElementType',
                  type: {
                    name: 'Composite',
                    className: 'IncomeStatement'
                  }
              }
            }
          },
          taxAreas: {
            required: false,
            serializedName: 'taxAreas',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'TaxAreaElementType',
                  type: {
                    name: 'Composite',
                    className: 'TaxArea'
                  }
              }
            }
          },
          salesQuotes: {
            required: false,
            serializedName: 'salesQuotes',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'SalesQuoteElementType',
                  type: {
                    name: 'Composite',
                    className: 'SalesQuote'
                  }
              }
            }
          },
          salesQuoteLines: {
            required: false,
            serializedName: 'salesQuoteLines',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'SalesQuoteLineElementType',
                  type: {
                    name: 'Composite',
                    className: 'SalesQuoteLine'
                  }
              }
            }
          },
          salesCreditMemos: {
            required: false,
            serializedName: 'salesCreditMemos',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'SalesCreditMemoElementType',
                  type: {
                    name: 'Composite',
                    className: 'SalesCreditMemo'
                  }
              }
            }
          },
          salesCreditMemoLines: {
            required: false,
            serializedName: 'salesCreditMemoLines',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'SalesCreditMemoLineElementType',
                  type: {
                    name: 'Composite',
                    className: 'SalesCreditMemoLine'
                  }
              }
            }
          },
          generalLedgerEntryAttachments: {
            required: false,
            serializedName: 'generalLedgerEntryAttachments',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'GeneralLedgerEntryAttachmentsElementType',
                  type: {
                    name: 'Composite',
                    className: 'GeneralLedgerEntryAttachments'
                  }
              }
            }
          },
          purchaseInvoices: {
            required: false,
            serializedName: 'purchaseInvoices',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'PurchaseInvoiceElementType',
                  type: {
                    name: 'Composite',
                    className: 'PurchaseInvoice'
                  }
              }
            }
          },
          purchaseInvoiceLines: {
            required: false,
            serializedName: 'purchaseInvoiceLines',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'PurchaseInvoiceLineElementType',
                  type: {
                    name: 'Composite',
                    className: 'PurchaseInvoiceLine'
                  }
              }
            }
          },
          customerSales: {
            required: false,
            serializedName: 'customerSales',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CustomerSaleElementType',
                  type: {
                    name: 'Composite',
                    className: 'CustomerSale'
                  }
              }
            }
          },
          vendorPurchases: {
            required: false,
            serializedName: 'vendorPurchases',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'VendorPurchaseElementType',
                  type: {
                    name: 'Composite',
                    className: 'VendorPurchase'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = Company;
