/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a CustomerPaymentJournal.
 */
class CustomerPaymentJournal {
  /**
   * Create a CustomerPaymentJournal.
   * @property {uuid} [id] The id property for the customerPaymentJournal
   * entity
   * @property {string} [code] The code property for the customerPaymentJournal
   * entity
   * @property {string} [displayName] The displayName property for the
   * customerPaymentJournal entity
   * @property {date} [lastModifiedDateTime] The lastModifiedDateTime property
   * for the customerPaymentJournal entity
   * @property {uuid} [balancingAccountId] The balancingAccountId property for
   * the customerPaymentJournal entity
   * @property {string} [balancingAccountNumber] The balancingAccountNumber
   * property for the customerPaymentJournal entity
   * @property {array} [customerPayments]
   * @property {object} [account]
   * @property {uuid} [account.id] The id property for the account entity
   * @property {string} [account.number] The number property for the account
   * entity
   * @property {string} [account.displayName] The displayName property for the
   * account entity
   * @property {string} [account.category] The category property for the
   * account entity
   * @property {string} [account.subCategory] The subCategory property for the
   * account entity
   * @property {boolean} [account.blocked] The blocked property for the account
   * entity
   * @property {date} [account.lastModifiedDateTime] The lastModifiedDateTime
   * property for the account entity
   */
  constructor() {
  }

  /**
   * Defines the metadata of CustomerPaymentJournal
   *
   * @returns {object} metadata of CustomerPaymentJournal
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'customerPaymentJournal',
      type: {
        name: 'Composite',
        className: 'CustomerPaymentJournal',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          code: {
            required: false,
            serializedName: 'code',
            constraints: {
              MaxLength: 10
            },
            type: {
              name: 'String'
            }
          },
          displayName: {
            required: false,
            serializedName: 'displayName',
            constraints: {
              MaxLength: 100
            },
            type: {
              name: 'String'
            }
          },
          lastModifiedDateTime: {
            required: false,
            serializedName: 'lastModifiedDateTime',
            type: {
              name: 'DateTime'
            }
          },
          balancingAccountId: {
            required: false,
            serializedName: 'balancingAccountId',
            type: {
              name: 'String'
            }
          },
          balancingAccountNumber: {
            required: false,
            serializedName: 'balancingAccountNumber',
            constraints: {
              MaxLength: 20
            },
            type: {
              name: 'String'
            }
          },
          customerPayments: {
            required: false,
            serializedName: 'customerPayments',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CustomerPaymentElementType',
                  type: {
                    name: 'Composite',
                    className: 'CustomerPayment'
                  }
              }
            }
          },
          account: {
            required: false,
            serializedName: 'account',
            type: {
              name: 'Composite',
              className: 'Account'
            }
          }
        }
      }
    };
  }
}

module.exports = CustomerPaymentJournal;
