/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a DefaultDimensions.
 */
class DefaultDimensions {
  /**
   * Create a DefaultDimensions.
   * @property {uuid} [parentId] The parentId property for the
   * defaultDimensions entity
   * @property {uuid} [dimensionId] The dimensionId property for the
   * defaultDimensions entity
   * @property {string} [dimensionCode] The dimensionCode property for the
   * defaultDimensions entity
   * @property {uuid} [dimensionValueId] The dimensionValueId property for the
   * defaultDimensions entity
   * @property {string} [dimensionValueCode] The dimensionValueCode property
   * for the defaultDimensions entity
   * @property {string} [postingValidation] The postingValidation property for
   * the defaultDimensions entity
   * @property {object} [account]
   * @property {uuid} [account.id] The id property for the account entity
   * @property {string} [account.number] The number property for the account
   * entity
   * @property {string} [account.displayName] The displayName property for the
   * account entity
   * @property {string} [account.category] The category property for the
   * account entity
   * @property {string} [account.subCategory] The subCategory property for the
   * account entity
   * @property {boolean} [account.blocked] The blocked property for the account
   * entity
   * @property {date} [account.lastModifiedDateTime] The lastModifiedDateTime
   * property for the account entity
   * @property {object} [dimension]
   * @property {uuid} [dimension.id] The id property for the dimension entity
   * @property {string} [dimension.code] The code property for the dimension
   * entity
   * @property {string} [dimension.displayName] The displayName property for
   * the dimension entity
   * @property {date} [dimension.lastModifiedDateTime] The lastModifiedDateTime
   * property for the dimension entity
   * @property {array} [dimension.dimensionValues]
   * @property {object} [dimensionValue]
   * @property {uuid} [dimensionValue.id] The id property for the
   * dimensionValue entity
   * @property {string} [dimensionValue.code] The code property for the
   * dimensionValue entity
   * @property {string} [dimensionValue.displayName] The displayName property
   * for the dimensionValue entity
   * @property {date} [dimensionValue.lastModifiedDateTime] The
   * lastModifiedDateTime property for the dimensionValue entity
   */
  constructor() {
  }

  /**
   * Defines the metadata of DefaultDimensions
   *
   * @returns {object} metadata of DefaultDimensions
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'defaultDimensions',
      type: {
        name: 'Composite',
        className: 'DefaultDimensions',
        modelProperties: {
          parentId: {
            required: false,
            serializedName: 'parentId',
            type: {
              name: 'String'
            }
          },
          dimensionId: {
            required: false,
            serializedName: 'dimensionId',
            type: {
              name: 'String'
            }
          },
          dimensionCode: {
            required: false,
            serializedName: 'dimensionCode',
            constraints: {
              MaxLength: 20
            },
            type: {
              name: 'String'
            }
          },
          dimensionValueId: {
            required: false,
            serializedName: 'dimensionValueId',
            type: {
              name: 'String'
            }
          },
          dimensionValueCode: {
            required: false,
            serializedName: 'dimensionValueCode',
            constraints: {
              MaxLength: 20
            },
            type: {
              name: 'String'
            }
          },
          postingValidation: {
            required: false,
            serializedName: 'postingValidation',
            type: {
              name: 'String'
            }
          },
          account: {
            required: false,
            serializedName: 'account',
            type: {
              name: 'Composite',
              className: 'Account'
            }
          },
          dimension: {
            required: false,
            serializedName: 'dimension',
            type: {
              name: 'Composite',
              className: 'Dimension'
            }
          },
          dimensionValue: {
            required: false,
            serializedName: 'dimensionValue',
            type: {
              name: 'Composite',
              className: 'DimensionValue'
            }
          }
        }
      }
    };
  }
}

module.exports = DefaultDimensions;
