/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Dimensiontype.
 */
class Dimensiontype {
  /**
   * Create a Dimensiontype.
   * @property {string} [code] The code property for the dimensiontype entity
   * @property {string} [displayName] The displayName property for the
   * dimensiontype entity
   * @property {string} [valueCode] The valueCode property for the
   * dimensiontype entity
   * @property {string} [valueDisplayName] The valueDisplayName property for
   * the dimensiontype entity
   * @property {object} [customer]
   * @property {uuid} [customer.id] The id property for the customer entity
   * @property {string} [customer.number] The number property for the customer
   * entity
   * @property {string} [customer.displayName] The displayName property for the
   * customer entity
   * @property {string} [customer.type] The type property for the customer
   * entity
   * @property {object} [customer.address]
   * @property {string} [customer.address.street] The street property for the
   * postaladdresstype entity
   * @property {string} [customer.address.city] The city property for the
   * postaladdresstype entity
   * @property {string} [customer.address.state] The state property for the
   * postaladdresstype entity
   * @property {string} [customer.address.countryLetterCode] The
   * countryLetterCode property for the postaladdresstype entity
   * @property {string} [customer.address.postalCode] The postalCode property
   * for the postaladdresstype entity
   * @property {array} [customer.address.customerFinancialDetails]
   * @property {array} [customer.address.picture]
   * @property {array} [customer.address.defaultDimensions]
   * @property {object} [customer.address.currency]
   * @property {uuid} [customer.address.currency.id] The id property for the
   * currency entity
   * @property {string} [customer.address.currency.code] The code property for
   * the currency entity
   * @property {string} [customer.address.currency.displayName] The displayName
   * property for the currency entity
   * @property {string} [customer.address.currency.symbol] The symbol property
   * for the currency entity
   * @property {string} [customer.address.currency.amountDecimalPlaces] The
   * amountDecimalPlaces property for the currency entity
   * @property {number} [customer.address.currency.amountRoundingPrecision] The
   * amountRoundingPrecision property for the currency entity
   * @property {date} [customer.address.currency.lastModifiedDateTime] The
   * lastModifiedDateTime property for the currency entity
   * @property {object} [customer.address.paymentTerm]
   * @property {uuid} [customer.address.paymentTerm.id] The id property for the
   * paymentTerm entity
   * @property {string} [customer.address.paymentTerm.code] The code property
   * for the paymentTerm entity
   * @property {string} [customer.address.paymentTerm.displayName] The
   * displayName property for the paymentTerm entity
   * @property {string} [customer.address.paymentTerm.dueDateCalculation] The
   * dueDateCalculation property for the paymentTerm entity
   * @property {string} [customer.address.paymentTerm.discountDateCalculation]
   * The discountDateCalculation property for the paymentTerm entity
   * @property {number} [customer.address.paymentTerm.discountPercent] The
   * discountPercent property for the paymentTerm entity
   * @property {boolean}
   * [customer.address.paymentTerm.calculateDiscountOnCreditMemos] The
   * calculateDiscountOnCreditMemos property for the paymentTerm entity
   * @property {date} [customer.address.paymentTerm.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentTerm entity
   * @property {object} [customer.address.shipmentMethod]
   * @property {uuid} [customer.address.shipmentMethod.id] The id property for
   * the shipmentMethod entity
   * @property {string} [customer.address.shipmentMethod.code] The code
   * property for the shipmentMethod entity
   * @property {string} [customer.address.shipmentMethod.displayName] The
   * displayName property for the shipmentMethod entity
   * @property {date} [customer.address.shipmentMethod.lastModifiedDateTime]
   * The lastModifiedDateTime property for the shipmentMethod entity
   * @property {object} [customer.address.paymentMethod]
   * @property {uuid} [customer.address.paymentMethod.id] The id property for
   * the paymentMethod entity
   * @property {string} [customer.address.paymentMethod.code] The code property
   * for the paymentMethod entity
   * @property {string} [customer.address.paymentMethod.displayName] The
   * displayName property for the paymentMethod entity
   * @property {date} [customer.address.paymentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentMethod entity
   * @property {string} [customer.phoneNumber] The phoneNumber property for the
   * customer entity
   * @property {string} [customer.email] The email property for the customer
   * entity
   * @property {string} [customer.website] The website property for the
   * customer entity
   * @property {boolean} [customer.taxLiable] The taxLiable property for the
   * customer entity
   * @property {uuid} [customer.taxAreaId] The taxAreaId property for the
   * customer entity
   * @property {string} [customer.taxAreaDisplayName] The taxAreaDisplayName
   * property for the customer entity
   * @property {string} [customer.taxRegistrationNumber] The
   * taxRegistrationNumber property for the customer entity
   * @property {uuid} [customer.currencyId] The currencyId property for the
   * customer entity
   * @property {string} [customer.currencyCode] The currencyCode property for
   * the customer entity
   * @property {uuid} [customer.paymentTermsId] The paymentTermsId property for
   * the customer entity
   * @property {uuid} [customer.shipmentMethodId] The shipmentMethodId property
   * for the customer entity
   * @property {uuid} [customer.paymentMethodId] The paymentMethodId property
   * for the customer entity
   * @property {string} [customer.blocked] The blocked property for the
   * customer entity
   * @property {date} [customer.lastModifiedDateTime] The lastModifiedDateTime
   * property for the customer entity
   * @property {array} [customer.customerFinancialDetails]
   * @property {array} [customer.picture]
   * @property {array} [customer.defaultDimensions]
   * @property {object} [customer.currency]
   * @property {uuid} [customer.currency.id] The id property for the currency
   * entity
   * @property {string} [customer.currency.code] The code property for the
   * currency entity
   * @property {string} [customer.currency.displayName] The displayName
   * property for the currency entity
   * @property {string} [customer.currency.symbol] The symbol property for the
   * currency entity
   * @property {string} [customer.currency.amountDecimalPlaces] The
   * amountDecimalPlaces property for the currency entity
   * @property {number} [customer.currency.amountRoundingPrecision] The
   * amountRoundingPrecision property for the currency entity
   * @property {date} [customer.currency.lastModifiedDateTime] The
   * lastModifiedDateTime property for the currency entity
   * @property {object} [customer.paymentTerm]
   * @property {uuid} [customer.paymentTerm.id] The id property for the
   * paymentTerm entity
   * @property {string} [customer.paymentTerm.code] The code property for the
   * paymentTerm entity
   * @property {string} [customer.paymentTerm.displayName] The displayName
   * property for the paymentTerm entity
   * @property {string} [customer.paymentTerm.dueDateCalculation] The
   * dueDateCalculation property for the paymentTerm entity
   * @property {string} [customer.paymentTerm.discountDateCalculation] The
   * discountDateCalculation property for the paymentTerm entity
   * @property {number} [customer.paymentTerm.discountPercent] The
   * discountPercent property for the paymentTerm entity
   * @property {boolean} [customer.paymentTerm.calculateDiscountOnCreditMemos]
   * The calculateDiscountOnCreditMemos property for the paymentTerm entity
   * @property {date} [customer.paymentTerm.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentTerm entity
   * @property {object} [customer.shipmentMethod]
   * @property {uuid} [customer.shipmentMethod.id] The id property for the
   * shipmentMethod entity
   * @property {string} [customer.shipmentMethod.code] The code property for
   * the shipmentMethod entity
   * @property {string} [customer.shipmentMethod.displayName] The displayName
   * property for the shipmentMethod entity
   * @property {date} [customer.shipmentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the shipmentMethod entity
   * @property {object} [customer.paymentMethod]
   * @property {uuid} [customer.paymentMethod.id] The id property for the
   * paymentMethod entity
   * @property {string} [customer.paymentMethod.code] The code property for the
   * paymentMethod entity
   * @property {string} [customer.paymentMethod.displayName] The displayName
   * property for the paymentMethod entity
   * @property {date} [customer.paymentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentMethod entity
   */
  constructor() {
  }

  /**
   * Defines the metadata of Dimensiontype
   *
   * @returns {object} metadata of Dimensiontype
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'dimensiontype',
      type: {
        name: 'Composite',
        className: 'Dimensiontype',
        modelProperties: {
          code: {
            required: false,
            serializedName: 'code',
            type: {
              name: 'String'
            }
          },
          displayName: {
            required: false,
            serializedName: 'displayName',
            type: {
              name: 'String'
            }
          },
          valueCode: {
            required: false,
            serializedName: 'valueCode',
            type: {
              name: 'String'
            }
          },
          valueDisplayName: {
            required: false,
            serializedName: 'valueDisplayName',
            type: {
              name: 'String'
            }
          },
          customer: {
            required: false,
            serializedName: 'customer',
            type: {
              name: 'Composite',
              className: 'Customer'
            }
          }
        }
      }
    };
  }
}

module.exports = Dimensiontype;
