/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a GetAttachmentsForJournalLineOKResponse.
 */
class GetAttachmentsForJournalLineOKResponse {
  /**
   * Create a GetAttachmentsForJournalLineOKResponse.
   * @property {array} [value]
   */
  constructor() {
  }

  /**
   * Defines the metadata of GetAttachmentsForJournalLineOKResponse
   *
   * @returns {object} metadata of GetAttachmentsForJournalLineOKResponse
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'GetAttachmentsForJournalLineOKResponse',
      type: {
        name: 'Composite',
        className: 'GetAttachmentsForJournalLineOKResponse',
        modelProperties: {
          value: {
            required: false,
            serializedName: 'value',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'AttachmentsElementType',
                  type: {
                    name: 'Composite',
                    className: 'Attachments'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = GetAttachmentsForJournalLineOKResponse;
