/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a IncomeStatement.
 */
class IncomeStatement {
  /**
   * Create a IncomeStatement.
   * @property {number} [lineNumber] The lineNumber property for the
   * incomeStatement entity
   * @property {string} [display] The display property for the incomeStatement
   * entity
   * @property {number} [netChange] The netChange property for the
   * incomeStatement entity
   * @property {string} [lineType] The lineType property for the
   * incomeStatement entity
   * @property {number} [indentation] The indentation property for the
   * incomeStatement entity
   * @property {date} [dateFilter] The dateFilter property for the
   * incomeStatement entity
   */
  constructor() {
  }

  /**
   * Defines the metadata of IncomeStatement
   *
   * @returns {object} metadata of IncomeStatement
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'incomeStatement',
      type: {
        name: 'Composite',
        className: 'IncomeStatement',
        modelProperties: {
          lineNumber: {
            required: false,
            serializedName: 'lineNumber',
            type: {
              name: 'Number'
            }
          },
          display: {
            required: false,
            serializedName: 'display',
            constraints: {
              MaxLength: 250
            },
            type: {
              name: 'String'
            }
          },
          netChange: {
            required: false,
            serializedName: 'netChange',
            type: {
              name: 'Number'
            }
          },
          lineType: {
            required: false,
            serializedName: 'lineType',
            constraints: {
              MaxLength: 30
            },
            type: {
              name: 'String'
            }
          },
          indentation: {
            required: false,
            serializedName: 'indentation',
            type: {
              name: 'Number'
            }
          },
          dateFilter: {
            required: false,
            serializedName: 'dateFilter',
            type: {
              name: 'DateTime'
            }
          }
        }
      }
    };
  }
}

module.exports = IncomeStatement;
