/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a ItemCategory.
 */
class ItemCategory {
  /**
   * Create a ItemCategory.
   * @property {uuid} [id] The id property for the itemCategory entity
   * @property {string} [code] The code property for the itemCategory entity
   * @property {string} [displayName] The displayName property for the
   * itemCategory entity
   * @property {date} [lastModifiedDateTime] The lastModifiedDateTime property
   * for the itemCategory entity
   */
  constructor() {
  }

  /**
   * Defines the metadata of ItemCategory
   *
   * @returns {object} metadata of ItemCategory
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'itemCategory',
      type: {
        name: 'Composite',
        className: 'ItemCategory',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          code: {
            required: false,
            serializedName: 'code',
            constraints: {
              MaxLength: 20
            },
            type: {
              name: 'String'
            }
          },
          displayName: {
            required: false,
            serializedName: 'displayName',
            constraints: {
              MaxLength: 100
            },
            type: {
              name: 'String'
            }
          },
          lastModifiedDateTime: {
            required: false,
            serializedName: 'lastModifiedDateTime',
            type: {
              name: 'DateTime'
            }
          }
        }
      }
    };
  }
}

module.exports = ItemCategory;
