/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a JournalLine.
 */
class JournalLine {
  /**
   * Create a JournalLine.
   * @property {uuid} [id] The id property for the journalLine entity
   * @property {string} [journalDisplayName] The journalDisplayName property
   * for the journalLine entity
   * @property {number} [lineNumber] The lineNumber property for the
   * journalLine entity
   * @property {uuid} [accountId] The accountId property for the journalLine
   * entity
   * @property {string} [accountNumber] The accountNumber property for the
   * journalLine entity
   * @property {date} [postingDate] The postingDate property for the
   * journalLine entity
   * @property {string} [documentNumber] The documentNumber property for the
   * journalLine entity
   * @property {string} [externalDocumentNumber] The externalDocumentNumber
   * property for the journalLine entity
   * @property {number} [amount] The amount property for the journalLine entity
   * @property {string} [description] The description property for the
   * journalLine entity
   * @property {string} [comment] The comment property for the journalLine
   * entity
   * @property {array} [dimensions]
   * @property {date} [lastModifiedDateTime] The lastModifiedDateTime property
   * for the journalLine entity
   * @property {array} [attachments]
   * @property {object} [account]
   * @property {uuid} [account.id] The id property for the account entity
   * @property {string} [account.number] The number property for the account
   * entity
   * @property {string} [account.displayName] The displayName property for the
   * account entity
   * @property {string} [account.category] The category property for the
   * account entity
   * @property {string} [account.subCategory] The subCategory property for the
   * account entity
   * @property {boolean} [account.blocked] The blocked property for the account
   * entity
   * @property {date} [account.lastModifiedDateTime] The lastModifiedDateTime
   * property for the account entity
   */
  constructor() {
  }

  /**
   * Defines the metadata of JournalLine
   *
   * @returns {object} metadata of JournalLine
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'journalLine',
      type: {
        name: 'Composite',
        className: 'JournalLine',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          journalDisplayName: {
            required: false,
            serializedName: 'journalDisplayName',
            type: {
              name: 'String'
            }
          },
          lineNumber: {
            required: false,
            serializedName: 'lineNumber',
            type: {
              name: 'Number'
            }
          },
          accountId: {
            required: false,
            serializedName: 'accountId',
            type: {
              name: 'String'
            }
          },
          accountNumber: {
            required: false,
            serializedName: 'accountNumber',
            constraints: {
              MaxLength: 20
            },
            type: {
              name: 'String'
            }
          },
          postingDate: {
            required: false,
            serializedName: 'postingDate',
            type: {
              name: 'DateTime'
            }
          },
          documentNumber: {
            required: false,
            serializedName: 'documentNumber',
            constraints: {
              MaxLength: 20
            },
            type: {
              name: 'String'
            }
          },
          externalDocumentNumber: {
            required: false,
            serializedName: 'externalDocumentNumber',
            constraints: {
              MaxLength: 35
            },
            type: {
              name: 'String'
            }
          },
          amount: {
            required: false,
            serializedName: 'amount',
            type: {
              name: 'Number'
            }
          },
          description: {
            required: false,
            serializedName: 'description',
            constraints: {
              MaxLength: 100
            },
            type: {
              name: 'String'
            }
          },
          comment: {
            required: false,
            serializedName: 'comment',
            constraints: {
              MaxLength: 250
            },
            type: {
              name: 'String'
            }
          },
          dimensions: {
            required: false,
            serializedName: 'dimensions',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'DimensiontypeElementType',
                  type: {
                    name: 'Composite',
                    className: 'Dimensiontype'
                  }
              }
            }
          },
          lastModifiedDateTime: {
            required: false,
            serializedName: 'lastModifiedDateTime',
            type: {
              name: 'DateTime'
            }
          },
          attachments: {
            required: false,
            serializedName: 'attachments',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'AttachmentsElementType',
                  type: {
                    name: 'Composite',
                    className: 'Attachments'
                  }
              }
            }
          },
          account: {
            required: false,
            serializedName: 'account',
            type: {
              name: 'Composite',
              className: 'Account'
            }
          }
        }
      }
    };
  }
}

module.exports = JournalLine;
