/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Picture.
 */
class Picture {
  /**
   * Create a Picture.
   * @property {uuid} [id] The id property for the picture entity
   * @property {number} [width] The width property for the picture entity
   * @property {number} [height] The height property for the picture entity
   * @property {string} [contentType] The contentType property for the picture
   * entity
   * @property {string} [content] The content property for the picture entity
   */
  constructor() {
  }

  /**
   * Defines the metadata of Picture
   *
   * @returns {object} metadata of Picture
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'picture',
      type: {
        name: 'Composite',
        className: 'Picture',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          width: {
            required: false,
            serializedName: 'width',
            type: {
              name: 'Number'
            }
          },
          height: {
            required: false,
            serializedName: 'height',
            type: {
              name: 'Number'
            }
          },
          contentType: {
            required: false,
            serializedName: 'contentType',
            constraints: {
              MaxLength: 100
            },
            type: {
              name: 'String'
            }
          },
          content: {
            required: false,
            serializedName: 'content',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Picture;
