/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a PurchaseInvoice.
 */
class PurchaseInvoice {
  /**
   * Create a PurchaseInvoice.
   * @property {uuid} [id] The id property for the purchaseInvoice entity
   * @property {string} [number] The number property for the purchaseInvoice
   * entity
   * @property {date} [invoiceDate] The invoiceDate property for the
   * purchaseInvoice entity
   * @property {date} [dueDate] The dueDate property for the purchaseInvoice
   * entity
   * @property {string} [vendorInvoiceNumber] The vendorInvoiceNumber property
   * for the purchaseInvoice entity
   * @property {uuid} [vendorId] The vendorId property for the purchaseInvoice
   * entity
   * @property {string} [vendorNumber] The vendorNumber property for the
   * purchaseInvoice entity
   * @property {string} [vendorName] The vendorName property for the
   * purchaseInvoice entity
   * @property {string} [payToName] The payToName property for the
   * purchaseInvoice entity
   * @property {string} [payToContact] The payToContact property for the
   * purchaseInvoice entity
   * @property {uuid} [payToVendorId] The payToVendorId property for the
   * purchaseInvoice entity
   * @property {string} [payToVendorNumber] The payToVendorNumber property for
   * the purchaseInvoice entity
   * @property {string} [shipToName] The shipToName property for the
   * purchaseInvoice entity
   * @property {string} [shipToContact] The shipToContact property for the
   * purchaseInvoice entity
   * @property {object} [buyFromAddress]
   * @property {string} [buyFromAddress.street] The street property for the
   * postaladdresstype entity
   * @property {string} [buyFromAddress.city] The city property for the
   * postaladdresstype entity
   * @property {string} [buyFromAddress.state] The state property for the
   * postaladdresstype entity
   * @property {string} [buyFromAddress.countryLetterCode] The
   * countryLetterCode property for the postaladdresstype entity
   * @property {string} [buyFromAddress.postalCode] The postalCode property for
   * the postaladdresstype entity
   * @property {array} [buyFromAddress.customerFinancialDetails]
   * @property {array} [buyFromAddress.picture]
   * @property {array} [buyFromAddress.defaultDimensions]
   * @property {object} [buyFromAddress.currency]
   * @property {uuid} [buyFromAddress.currency.id] The id property for the
   * currency entity
   * @property {string} [buyFromAddress.currency.code] The code property for
   * the currency entity
   * @property {string} [buyFromAddress.currency.displayName] The displayName
   * property for the currency entity
   * @property {string} [buyFromAddress.currency.symbol] The symbol property
   * for the currency entity
   * @property {string} [buyFromAddress.currency.amountDecimalPlaces] The
   * amountDecimalPlaces property for the currency entity
   * @property {number} [buyFromAddress.currency.amountRoundingPrecision] The
   * amountRoundingPrecision property for the currency entity
   * @property {date} [buyFromAddress.currency.lastModifiedDateTime] The
   * lastModifiedDateTime property for the currency entity
   * @property {object} [buyFromAddress.paymentTerm]
   * @property {uuid} [buyFromAddress.paymentTerm.id] The id property for the
   * paymentTerm entity
   * @property {string} [buyFromAddress.paymentTerm.code] The code property for
   * the paymentTerm entity
   * @property {string} [buyFromAddress.paymentTerm.displayName] The
   * displayName property for the paymentTerm entity
   * @property {string} [buyFromAddress.paymentTerm.dueDateCalculation] The
   * dueDateCalculation property for the paymentTerm entity
   * @property {string} [buyFromAddress.paymentTerm.discountDateCalculation]
   * The discountDateCalculation property for the paymentTerm entity
   * @property {number} [buyFromAddress.paymentTerm.discountPercent] The
   * discountPercent property for the paymentTerm entity
   * @property {boolean}
   * [buyFromAddress.paymentTerm.calculateDiscountOnCreditMemos] The
   * calculateDiscountOnCreditMemos property for the paymentTerm entity
   * @property {date} [buyFromAddress.paymentTerm.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentTerm entity
   * @property {object} [buyFromAddress.shipmentMethod]
   * @property {uuid} [buyFromAddress.shipmentMethod.id] The id property for
   * the shipmentMethod entity
   * @property {string} [buyFromAddress.shipmentMethod.code] The code property
   * for the shipmentMethod entity
   * @property {string} [buyFromAddress.shipmentMethod.displayName] The
   * displayName property for the shipmentMethod entity
   * @property {date} [buyFromAddress.shipmentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the shipmentMethod entity
   * @property {object} [buyFromAddress.paymentMethod]
   * @property {uuid} [buyFromAddress.paymentMethod.id] The id property for the
   * paymentMethod entity
   * @property {string} [buyFromAddress.paymentMethod.code] The code property
   * for the paymentMethod entity
   * @property {string} [buyFromAddress.paymentMethod.displayName] The
   * displayName property for the paymentMethod entity
   * @property {date} [buyFromAddress.paymentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentMethod entity
   * @property {object} [payToAddress]
   * @property {string} [payToAddress.street] The street property for the
   * postaladdresstype entity
   * @property {string} [payToAddress.city] The city property for the
   * postaladdresstype entity
   * @property {string} [payToAddress.state] The state property for the
   * postaladdresstype entity
   * @property {string} [payToAddress.countryLetterCode] The countryLetterCode
   * property for the postaladdresstype entity
   * @property {string} [payToAddress.postalCode] The postalCode property for
   * the postaladdresstype entity
   * @property {array} [payToAddress.customerFinancialDetails]
   * @property {array} [payToAddress.picture]
   * @property {array} [payToAddress.defaultDimensions]
   * @property {object} [payToAddress.currency]
   * @property {uuid} [payToAddress.currency.id] The id property for the
   * currency entity
   * @property {string} [payToAddress.currency.code] The code property for the
   * currency entity
   * @property {string} [payToAddress.currency.displayName] The displayName
   * property for the currency entity
   * @property {string} [payToAddress.currency.symbol] The symbol property for
   * the currency entity
   * @property {string} [payToAddress.currency.amountDecimalPlaces] The
   * amountDecimalPlaces property for the currency entity
   * @property {number} [payToAddress.currency.amountRoundingPrecision] The
   * amountRoundingPrecision property for the currency entity
   * @property {date} [payToAddress.currency.lastModifiedDateTime] The
   * lastModifiedDateTime property for the currency entity
   * @property {object} [payToAddress.paymentTerm]
   * @property {uuid} [payToAddress.paymentTerm.id] The id property for the
   * paymentTerm entity
   * @property {string} [payToAddress.paymentTerm.code] The code property for
   * the paymentTerm entity
   * @property {string} [payToAddress.paymentTerm.displayName] The displayName
   * property for the paymentTerm entity
   * @property {string} [payToAddress.paymentTerm.dueDateCalculation] The
   * dueDateCalculation property for the paymentTerm entity
   * @property {string} [payToAddress.paymentTerm.discountDateCalculation] The
   * discountDateCalculation property for the paymentTerm entity
   * @property {number} [payToAddress.paymentTerm.discountPercent] The
   * discountPercent property for the paymentTerm entity
   * @property {boolean}
   * [payToAddress.paymentTerm.calculateDiscountOnCreditMemos] The
   * calculateDiscountOnCreditMemos property for the paymentTerm entity
   * @property {date} [payToAddress.paymentTerm.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentTerm entity
   * @property {object} [payToAddress.shipmentMethod]
   * @property {uuid} [payToAddress.shipmentMethod.id] The id property for the
   * shipmentMethod entity
   * @property {string} [payToAddress.shipmentMethod.code] The code property
   * for the shipmentMethod entity
   * @property {string} [payToAddress.shipmentMethod.displayName] The
   * displayName property for the shipmentMethod entity
   * @property {date} [payToAddress.shipmentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the shipmentMethod entity
   * @property {object} [payToAddress.paymentMethod]
   * @property {uuid} [payToAddress.paymentMethod.id] The id property for the
   * paymentMethod entity
   * @property {string} [payToAddress.paymentMethod.code] The code property for
   * the paymentMethod entity
   * @property {string} [payToAddress.paymentMethod.displayName] The
   * displayName property for the paymentMethod entity
   * @property {date} [payToAddress.paymentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentMethod entity
   * @property {object} [shipToAddress]
   * @property {string} [shipToAddress.street] The street property for the
   * postaladdresstype entity
   * @property {string} [shipToAddress.city] The city property for the
   * postaladdresstype entity
   * @property {string} [shipToAddress.state] The state property for the
   * postaladdresstype entity
   * @property {string} [shipToAddress.countryLetterCode] The countryLetterCode
   * property for the postaladdresstype entity
   * @property {string} [shipToAddress.postalCode] The postalCode property for
   * the postaladdresstype entity
   * @property {array} [shipToAddress.customerFinancialDetails]
   * @property {array} [shipToAddress.picture]
   * @property {array} [shipToAddress.defaultDimensions]
   * @property {object} [shipToAddress.currency]
   * @property {uuid} [shipToAddress.currency.id] The id property for the
   * currency entity
   * @property {string} [shipToAddress.currency.code] The code property for the
   * currency entity
   * @property {string} [shipToAddress.currency.displayName] The displayName
   * property for the currency entity
   * @property {string} [shipToAddress.currency.symbol] The symbol property for
   * the currency entity
   * @property {string} [shipToAddress.currency.amountDecimalPlaces] The
   * amountDecimalPlaces property for the currency entity
   * @property {number} [shipToAddress.currency.amountRoundingPrecision] The
   * amountRoundingPrecision property for the currency entity
   * @property {date} [shipToAddress.currency.lastModifiedDateTime] The
   * lastModifiedDateTime property for the currency entity
   * @property {object} [shipToAddress.paymentTerm]
   * @property {uuid} [shipToAddress.paymentTerm.id] The id property for the
   * paymentTerm entity
   * @property {string} [shipToAddress.paymentTerm.code] The code property for
   * the paymentTerm entity
   * @property {string} [shipToAddress.paymentTerm.displayName] The displayName
   * property for the paymentTerm entity
   * @property {string} [shipToAddress.paymentTerm.dueDateCalculation] The
   * dueDateCalculation property for the paymentTerm entity
   * @property {string} [shipToAddress.paymentTerm.discountDateCalculation] The
   * discountDateCalculation property for the paymentTerm entity
   * @property {number} [shipToAddress.paymentTerm.discountPercent] The
   * discountPercent property for the paymentTerm entity
   * @property {boolean}
   * [shipToAddress.paymentTerm.calculateDiscountOnCreditMemos] The
   * calculateDiscountOnCreditMemos property for the paymentTerm entity
   * @property {date} [shipToAddress.paymentTerm.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentTerm entity
   * @property {object} [shipToAddress.shipmentMethod]
   * @property {uuid} [shipToAddress.shipmentMethod.id] The id property for the
   * shipmentMethod entity
   * @property {string} [shipToAddress.shipmentMethod.code] The code property
   * for the shipmentMethod entity
   * @property {string} [shipToAddress.shipmentMethod.displayName] The
   * displayName property for the shipmentMethod entity
   * @property {date} [shipToAddress.shipmentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the shipmentMethod entity
   * @property {object} [shipToAddress.paymentMethod]
   * @property {uuid} [shipToAddress.paymentMethod.id] The id property for the
   * paymentMethod entity
   * @property {string} [shipToAddress.paymentMethod.code] The code property
   * for the paymentMethod entity
   * @property {string} [shipToAddress.paymentMethod.displayName] The
   * displayName property for the paymentMethod entity
   * @property {date} [shipToAddress.paymentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentMethod entity
   * @property {uuid} [currencyId] The currencyId property for the
   * purchaseInvoice entity
   * @property {string} [currencyCode] The currencyCode property for the
   * purchaseInvoice entity
   * @property {boolean} [pricesIncludeTax] The pricesIncludeTax property for
   * the purchaseInvoice entity
   * @property {number} [discountAmount] The discountAmount property for the
   * purchaseInvoice entity
   * @property {boolean} [discountAppliedBeforeTax] The
   * discountAppliedBeforeTax property for the purchaseInvoice entity
   * @property {number} [totalAmountExcludingTax] The totalAmountExcludingTax
   * property for the purchaseInvoice entity
   * @property {number} [totalTaxAmount] The totalTaxAmount property for the
   * purchaseInvoice entity
   * @property {number} [totalAmountIncludingTax] The totalAmountIncludingTax
   * property for the purchaseInvoice entity
   * @property {string} [status] The status property for the purchaseInvoice
   * entity
   * @property {date} [lastModifiedDateTime] The lastModifiedDateTime property
   * for the purchaseInvoice entity
   * @property {array} [purchaseInvoiceLines]
   * @property {array} [pdfDocument]
   * @property {object} [vendor]
   * @property {uuid} [vendor.id] The id property for the vendor entity
   * @property {string} [vendor.number] The number property for the vendor
   * entity
   * @property {string} [vendor.displayName] The displayName property for the
   * vendor entity
   * @property {object} [vendor.address]
   * @property {string} [vendor.address.street] The street property for the
   * postaladdresstype entity
   * @property {string} [vendor.address.city] The city property for the
   * postaladdresstype entity
   * @property {string} [vendor.address.state] The state property for the
   * postaladdresstype entity
   * @property {string} [vendor.address.countryLetterCode] The
   * countryLetterCode property for the postaladdresstype entity
   * @property {string} [vendor.address.postalCode] The postalCode property for
   * the postaladdresstype entity
   * @property {array} [vendor.address.customerFinancialDetails]
   * @property {array} [vendor.address.picture]
   * @property {array} [vendor.address.defaultDimensions]
   * @property {object} [vendor.address.currency]
   * @property {uuid} [vendor.address.currency.id] The id property for the
   * currency entity
   * @property {string} [vendor.address.currency.code] The code property for
   * the currency entity
   * @property {string} [vendor.address.currency.displayName] The displayName
   * property for the currency entity
   * @property {string} [vendor.address.currency.symbol] The symbol property
   * for the currency entity
   * @property {string} [vendor.address.currency.amountDecimalPlaces] The
   * amountDecimalPlaces property for the currency entity
   * @property {number} [vendor.address.currency.amountRoundingPrecision] The
   * amountRoundingPrecision property for the currency entity
   * @property {date} [vendor.address.currency.lastModifiedDateTime] The
   * lastModifiedDateTime property for the currency entity
   * @property {object} [vendor.address.paymentTerm]
   * @property {uuid} [vendor.address.paymentTerm.id] The id property for the
   * paymentTerm entity
   * @property {string} [vendor.address.paymentTerm.code] The code property for
   * the paymentTerm entity
   * @property {string} [vendor.address.paymentTerm.displayName] The
   * displayName property for the paymentTerm entity
   * @property {string} [vendor.address.paymentTerm.dueDateCalculation] The
   * dueDateCalculation property for the paymentTerm entity
   * @property {string} [vendor.address.paymentTerm.discountDateCalculation]
   * The discountDateCalculation property for the paymentTerm entity
   * @property {number} [vendor.address.paymentTerm.discountPercent] The
   * discountPercent property for the paymentTerm entity
   * @property {boolean}
   * [vendor.address.paymentTerm.calculateDiscountOnCreditMemos] The
   * calculateDiscountOnCreditMemos property for the paymentTerm entity
   * @property {date} [vendor.address.paymentTerm.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentTerm entity
   * @property {object} [vendor.address.shipmentMethod]
   * @property {uuid} [vendor.address.shipmentMethod.id] The id property for
   * the shipmentMethod entity
   * @property {string} [vendor.address.shipmentMethod.code] The code property
   * for the shipmentMethod entity
   * @property {string} [vendor.address.shipmentMethod.displayName] The
   * displayName property for the shipmentMethod entity
   * @property {date} [vendor.address.shipmentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the shipmentMethod entity
   * @property {object} [vendor.address.paymentMethod]
   * @property {uuid} [vendor.address.paymentMethod.id] The id property for the
   * paymentMethod entity
   * @property {string} [vendor.address.paymentMethod.code] The code property
   * for the paymentMethod entity
   * @property {string} [vendor.address.paymentMethod.displayName] The
   * displayName property for the paymentMethod entity
   * @property {date} [vendor.address.paymentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentMethod entity
   * @property {string} [vendor.phoneNumber] The phoneNumber property for the
   * vendor entity
   * @property {string} [vendor.email] The email property for the vendor entity
   * @property {string} [vendor.website] The website property for the vendor
   * entity
   * @property {string} [vendor.taxRegistrationNumber] The
   * taxRegistrationNumber property for the vendor entity
   * @property {uuid} [vendor.currencyId] The currencyId property for the
   * vendor entity
   * @property {string} [vendor.currencyCode] The currencyCode property for the
   * vendor entity
   * @property {string} [vendor.irs1099Code] The irs1099Code property for the
   * vendor entity
   * @property {uuid} [vendor.paymentTermsId] The paymentTermsId property for
   * the vendor entity
   * @property {uuid} [vendor.paymentMethodId] The paymentMethodId property for
   * the vendor entity
   * @property {boolean} [vendor.taxLiable] The taxLiable property for the
   * vendor entity
   * @property {string} [vendor.blocked] The blocked property for the vendor
   * entity
   * @property {number} [vendor.balance] The balance property for the vendor
   * entity
   * @property {date} [vendor.lastModifiedDateTime] The lastModifiedDateTime
   * property for the vendor entity
   * @property {array} [vendor.picture]
   * @property {array} [vendor.defaultDimensions]
   * @property {object} [vendor.currency]
   * @property {uuid} [vendor.currency.id] The id property for the currency
   * entity
   * @property {string} [vendor.currency.code] The code property for the
   * currency entity
   * @property {string} [vendor.currency.displayName] The displayName property
   * for the currency entity
   * @property {string} [vendor.currency.symbol] The symbol property for the
   * currency entity
   * @property {string} [vendor.currency.amountDecimalPlaces] The
   * amountDecimalPlaces property for the currency entity
   * @property {number} [vendor.currency.amountRoundingPrecision] The
   * amountRoundingPrecision property for the currency entity
   * @property {date} [vendor.currency.lastModifiedDateTime] The
   * lastModifiedDateTime property for the currency entity
   * @property {object} [vendor.paymentTerm]
   * @property {uuid} [vendor.paymentTerm.id] The id property for the
   * paymentTerm entity
   * @property {string} [vendor.paymentTerm.code] The code property for the
   * paymentTerm entity
   * @property {string} [vendor.paymentTerm.displayName] The displayName
   * property for the paymentTerm entity
   * @property {string} [vendor.paymentTerm.dueDateCalculation] The
   * dueDateCalculation property for the paymentTerm entity
   * @property {string} [vendor.paymentTerm.discountDateCalculation] The
   * discountDateCalculation property for the paymentTerm entity
   * @property {number} [vendor.paymentTerm.discountPercent] The
   * discountPercent property for the paymentTerm entity
   * @property {boolean} [vendor.paymentTerm.calculateDiscountOnCreditMemos]
   * The calculateDiscountOnCreditMemos property for the paymentTerm entity
   * @property {date} [vendor.paymentTerm.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentTerm entity
   * @property {object} [vendor.paymentMethod]
   * @property {uuid} [vendor.paymentMethod.id] The id property for the
   * paymentMethod entity
   * @property {string} [vendor.paymentMethod.code] The code property for the
   * paymentMethod entity
   * @property {string} [vendor.paymentMethod.displayName] The displayName
   * property for the paymentMethod entity
   * @property {date} [vendor.paymentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentMethod entity
   * @property {object} [currency]
   * @property {uuid} [currency.id] The id property for the currency entity
   * @property {string} [currency.code] The code property for the currency
   * entity
   * @property {string} [currency.displayName] The displayName property for the
   * currency entity
   * @property {string} [currency.symbol] The symbol property for the currency
   * entity
   * @property {string} [currency.amountDecimalPlaces] The amountDecimalPlaces
   * property for the currency entity
   * @property {number} [currency.amountRoundingPrecision] The
   * amountRoundingPrecision property for the currency entity
   * @property {date} [currency.lastModifiedDateTime] The lastModifiedDateTime
   * property for the currency entity
   */
  constructor() {
  }

  /**
   * Defines the metadata of PurchaseInvoice
   *
   * @returns {object} metadata of PurchaseInvoice
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'purchaseInvoice',
      type: {
        name: 'Composite',
        className: 'PurchaseInvoice',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          number: {
            required: false,
            serializedName: 'number',
            constraints: {
              MaxLength: 20
            },
            type: {
              name: 'String'
            }
          },
          invoiceDate: {
            required: false,
            serializedName: 'invoiceDate',
            type: {
              name: 'DateTime'
            }
          },
          dueDate: {
            required: false,
            serializedName: 'dueDate',
            type: {
              name: 'DateTime'
            }
          },
          vendorInvoiceNumber: {
            required: false,
            serializedName: 'vendorInvoiceNumber',
            constraints: {
              MaxLength: 35
            },
            type: {
              name: 'String'
            }
          },
          vendorId: {
            required: false,
            serializedName: 'vendorId',
            type: {
              name: 'String'
            }
          },
          vendorNumber: {
            required: false,
            serializedName: 'vendorNumber',
            constraints: {
              MaxLength: 20
            },
            type: {
              name: 'String'
            }
          },
          vendorName: {
            required: false,
            serializedName: 'vendorName',
            constraints: {
              MaxLength: 100
            },
            type: {
              name: 'String'
            }
          },
          payToName: {
            required: false,
            serializedName: 'payToName',
            constraints: {
              MaxLength: 100
            },
            type: {
              name: 'String'
            }
          },
          payToContact: {
            required: false,
            serializedName: 'payToContact',
            constraints: {
              MaxLength: 100
            },
            type: {
              name: 'String'
            }
          },
          payToVendorId: {
            required: false,
            serializedName: 'payToVendorId',
            type: {
              name: 'String'
            }
          },
          payToVendorNumber: {
            required: false,
            serializedName: 'payToVendorNumber',
            constraints: {
              MaxLength: 20
            },
            type: {
              name: 'String'
            }
          },
          shipToName: {
            required: false,
            serializedName: 'shipToName',
            constraints: {
              MaxLength: 100
            },
            type: {
              name: 'String'
            }
          },
          shipToContact: {
            required: false,
            serializedName: 'shipToContact',
            constraints: {
              MaxLength: 100
            },
            type: {
              name: 'String'
            }
          },
          buyFromAddress: {
            required: false,
            serializedName: 'buyFromAddress',
            type: {
              name: 'Composite',
              className: 'Postaladdresstype'
            }
          },
          payToAddress: {
            required: false,
            serializedName: 'payToAddress',
            type: {
              name: 'Composite',
              className: 'Postaladdresstype'
            }
          },
          shipToAddress: {
            required: false,
            serializedName: 'shipToAddress',
            type: {
              name: 'Composite',
              className: 'Postaladdresstype'
            }
          },
          currencyId: {
            required: false,
            serializedName: 'currencyId',
            type: {
              name: 'String'
            }
          },
          currencyCode: {
            required: false,
            serializedName: 'currencyCode',
            type: {
              name: 'String'
            }
          },
          pricesIncludeTax: {
            required: false,
            serializedName: 'pricesIncludeTax',
            type: {
              name: 'Boolean'
            }
          },
          discountAmount: {
            required: false,
            serializedName: 'discountAmount',
            type: {
              name: 'Number'
            }
          },
          discountAppliedBeforeTax: {
            required: false,
            serializedName: 'discountAppliedBeforeTax',
            type: {
              name: 'Boolean'
            }
          },
          totalAmountExcludingTax: {
            required: false,
            serializedName: 'totalAmountExcludingTax',
            type: {
              name: 'Number'
            }
          },
          totalTaxAmount: {
            required: false,
            serializedName: 'totalTaxAmount',
            type: {
              name: 'Number'
            }
          },
          totalAmountIncludingTax: {
            required: false,
            serializedName: 'totalAmountIncludingTax',
            type: {
              name: 'Number'
            }
          },
          status: {
            required: false,
            serializedName: 'status',
            type: {
              name: 'String'
            }
          },
          lastModifiedDateTime: {
            required: false,
            serializedName: 'lastModifiedDateTime',
            type: {
              name: 'DateTime'
            }
          },
          purchaseInvoiceLines: {
            required: false,
            serializedName: 'purchaseInvoiceLines',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'PurchaseInvoiceLineElementType',
                  type: {
                    name: 'Composite',
                    className: 'PurchaseInvoiceLine'
                  }
              }
            }
          },
          pdfDocument: {
            required: false,
            serializedName: 'pdfDocument',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'PdfDocumentElementType',
                  type: {
                    name: 'Composite',
                    className: 'PdfDocument'
                  }
              }
            }
          },
          vendor: {
            required: false,
            serializedName: 'vendor',
            type: {
              name: 'Composite',
              className: 'Vendor'
            }
          },
          currency: {
            required: false,
            serializedName: 'currency',
            type: {
              name: 'Composite',
              className: 'Currency'
            }
          }
        }
      }
    };
  }
}

module.exports = PurchaseInvoice;
