/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a SalesInvoice.
 */
class SalesInvoice {
  /**
   * Create a SalesInvoice.
   * @property {uuid} [id] The id property for the salesInvoice entity
   * @property {string} [number] The number property for the salesInvoice
   * entity
   * @property {string} [externalDocumentNumber] The externalDocumentNumber
   * property for the salesInvoice entity
   * @property {date} [invoiceDate] The invoiceDate property for the
   * salesInvoice entity
   * @property {date} [dueDate] The dueDate property for the salesInvoice
   * entity
   * @property {string} [customerPurchaseOrderReference] The
   * customerPurchaseOrderReference property for the salesInvoice entity
   * @property {uuid} [customerId] The customerId property for the salesInvoice
   * entity
   * @property {string} [contactId] The contactId property for the salesInvoice
   * entity
   * @property {string} [customerNumber] The customerNumber property for the
   * salesInvoice entity
   * @property {string} [customerName] The customerName property for the
   * salesInvoice entity
   * @property {string} [billToName] The billToName property for the
   * salesInvoice entity
   * @property {uuid} [billToCustomerId] The billToCustomerId property for the
   * salesInvoice entity
   * @property {string} [billToCustomerNumber] The billToCustomerNumber
   * property for the salesInvoice entity
   * @property {string} [shipToName] The shipToName property for the
   * salesInvoice entity
   * @property {string} [shipToContact] The shipToContact property for the
   * salesInvoice entity
   * @property {object} [sellingPostalAddress]
   * @property {string} [sellingPostalAddress.street] The street property for
   * the postaladdresstype entity
   * @property {string} [sellingPostalAddress.city] The city property for the
   * postaladdresstype entity
   * @property {string} [sellingPostalAddress.state] The state property for the
   * postaladdresstype entity
   * @property {string} [sellingPostalAddress.countryLetterCode] The
   * countryLetterCode property for the postaladdresstype entity
   * @property {string} [sellingPostalAddress.postalCode] The postalCode
   * property for the postaladdresstype entity
   * @property {array} [sellingPostalAddress.customerFinancialDetails]
   * @property {array} [sellingPostalAddress.picture]
   * @property {array} [sellingPostalAddress.defaultDimensions]
   * @property {object} [sellingPostalAddress.currency]
   * @property {uuid} [sellingPostalAddress.currency.id] The id property for
   * the currency entity
   * @property {string} [sellingPostalAddress.currency.code] The code property
   * for the currency entity
   * @property {string} [sellingPostalAddress.currency.displayName] The
   * displayName property for the currency entity
   * @property {string} [sellingPostalAddress.currency.symbol] The symbol
   * property for the currency entity
   * @property {string} [sellingPostalAddress.currency.amountDecimalPlaces] The
   * amountDecimalPlaces property for the currency entity
   * @property {number} [sellingPostalAddress.currency.amountRoundingPrecision]
   * The amountRoundingPrecision property for the currency entity
   * @property {date} [sellingPostalAddress.currency.lastModifiedDateTime] The
   * lastModifiedDateTime property for the currency entity
   * @property {object} [sellingPostalAddress.paymentTerm]
   * @property {uuid} [sellingPostalAddress.paymentTerm.id] The id property for
   * the paymentTerm entity
   * @property {string} [sellingPostalAddress.paymentTerm.code] The code
   * property for the paymentTerm entity
   * @property {string} [sellingPostalAddress.paymentTerm.displayName] The
   * displayName property for the paymentTerm entity
   * @property {string} [sellingPostalAddress.paymentTerm.dueDateCalculation]
   * The dueDateCalculation property for the paymentTerm entity
   * @property {string}
   * [sellingPostalAddress.paymentTerm.discountDateCalculation] The
   * discountDateCalculation property for the paymentTerm entity
   * @property {number} [sellingPostalAddress.paymentTerm.discountPercent] The
   * discountPercent property for the paymentTerm entity
   * @property {boolean}
   * [sellingPostalAddress.paymentTerm.calculateDiscountOnCreditMemos] The
   * calculateDiscountOnCreditMemos property for the paymentTerm entity
   * @property {date} [sellingPostalAddress.paymentTerm.lastModifiedDateTime]
   * The lastModifiedDateTime property for the paymentTerm entity
   * @property {object} [sellingPostalAddress.shipmentMethod]
   * @property {uuid} [sellingPostalAddress.shipmentMethod.id] The id property
   * for the shipmentMethod entity
   * @property {string} [sellingPostalAddress.shipmentMethod.code] The code
   * property for the shipmentMethod entity
   * @property {string} [sellingPostalAddress.shipmentMethod.displayName] The
   * displayName property for the shipmentMethod entity
   * @property {date}
   * [sellingPostalAddress.shipmentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the shipmentMethod entity
   * @property {object} [sellingPostalAddress.paymentMethod]
   * @property {uuid} [sellingPostalAddress.paymentMethod.id] The id property
   * for the paymentMethod entity
   * @property {string} [sellingPostalAddress.paymentMethod.code] The code
   * property for the paymentMethod entity
   * @property {string} [sellingPostalAddress.paymentMethod.displayName] The
   * displayName property for the paymentMethod entity
   * @property {date} [sellingPostalAddress.paymentMethod.lastModifiedDateTime]
   * The lastModifiedDateTime property for the paymentMethod entity
   * @property {object} [billingPostalAddress]
   * @property {string} [billingPostalAddress.street] The street property for
   * the postaladdresstype entity
   * @property {string} [billingPostalAddress.city] The city property for the
   * postaladdresstype entity
   * @property {string} [billingPostalAddress.state] The state property for the
   * postaladdresstype entity
   * @property {string} [billingPostalAddress.countryLetterCode] The
   * countryLetterCode property for the postaladdresstype entity
   * @property {string} [billingPostalAddress.postalCode] The postalCode
   * property for the postaladdresstype entity
   * @property {array} [billingPostalAddress.customerFinancialDetails]
   * @property {array} [billingPostalAddress.picture]
   * @property {array} [billingPostalAddress.defaultDimensions]
   * @property {object} [billingPostalAddress.currency]
   * @property {uuid} [billingPostalAddress.currency.id] The id property for
   * the currency entity
   * @property {string} [billingPostalAddress.currency.code] The code property
   * for the currency entity
   * @property {string} [billingPostalAddress.currency.displayName] The
   * displayName property for the currency entity
   * @property {string} [billingPostalAddress.currency.symbol] The symbol
   * property for the currency entity
   * @property {string} [billingPostalAddress.currency.amountDecimalPlaces] The
   * amountDecimalPlaces property for the currency entity
   * @property {number} [billingPostalAddress.currency.amountRoundingPrecision]
   * The amountRoundingPrecision property for the currency entity
   * @property {date} [billingPostalAddress.currency.lastModifiedDateTime] The
   * lastModifiedDateTime property for the currency entity
   * @property {object} [billingPostalAddress.paymentTerm]
   * @property {uuid} [billingPostalAddress.paymentTerm.id] The id property for
   * the paymentTerm entity
   * @property {string} [billingPostalAddress.paymentTerm.code] The code
   * property for the paymentTerm entity
   * @property {string} [billingPostalAddress.paymentTerm.displayName] The
   * displayName property for the paymentTerm entity
   * @property {string} [billingPostalAddress.paymentTerm.dueDateCalculation]
   * The dueDateCalculation property for the paymentTerm entity
   * @property {string}
   * [billingPostalAddress.paymentTerm.discountDateCalculation] The
   * discountDateCalculation property for the paymentTerm entity
   * @property {number} [billingPostalAddress.paymentTerm.discountPercent] The
   * discountPercent property for the paymentTerm entity
   * @property {boolean}
   * [billingPostalAddress.paymentTerm.calculateDiscountOnCreditMemos] The
   * calculateDiscountOnCreditMemos property for the paymentTerm entity
   * @property {date} [billingPostalAddress.paymentTerm.lastModifiedDateTime]
   * The lastModifiedDateTime property for the paymentTerm entity
   * @property {object} [billingPostalAddress.shipmentMethod]
   * @property {uuid} [billingPostalAddress.shipmentMethod.id] The id property
   * for the shipmentMethod entity
   * @property {string} [billingPostalAddress.shipmentMethod.code] The code
   * property for the shipmentMethod entity
   * @property {string} [billingPostalAddress.shipmentMethod.displayName] The
   * displayName property for the shipmentMethod entity
   * @property {date}
   * [billingPostalAddress.shipmentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the shipmentMethod entity
   * @property {object} [billingPostalAddress.paymentMethod]
   * @property {uuid} [billingPostalAddress.paymentMethod.id] The id property
   * for the paymentMethod entity
   * @property {string} [billingPostalAddress.paymentMethod.code] The code
   * property for the paymentMethod entity
   * @property {string} [billingPostalAddress.paymentMethod.displayName] The
   * displayName property for the paymentMethod entity
   * @property {date} [billingPostalAddress.paymentMethod.lastModifiedDateTime]
   * The lastModifiedDateTime property for the paymentMethod entity
   * @property {object} [shippingPostalAddress]
   * @property {string} [shippingPostalAddress.street] The street property for
   * the postaladdresstype entity
   * @property {string} [shippingPostalAddress.city] The city property for the
   * postaladdresstype entity
   * @property {string} [shippingPostalAddress.state] The state property for
   * the postaladdresstype entity
   * @property {string} [shippingPostalAddress.countryLetterCode] The
   * countryLetterCode property for the postaladdresstype entity
   * @property {string} [shippingPostalAddress.postalCode] The postalCode
   * property for the postaladdresstype entity
   * @property {array} [shippingPostalAddress.customerFinancialDetails]
   * @property {array} [shippingPostalAddress.picture]
   * @property {array} [shippingPostalAddress.defaultDimensions]
   * @property {object} [shippingPostalAddress.currency]
   * @property {uuid} [shippingPostalAddress.currency.id] The id property for
   * the currency entity
   * @property {string} [shippingPostalAddress.currency.code] The code property
   * for the currency entity
   * @property {string} [shippingPostalAddress.currency.displayName] The
   * displayName property for the currency entity
   * @property {string} [shippingPostalAddress.currency.symbol] The symbol
   * property for the currency entity
   * @property {string} [shippingPostalAddress.currency.amountDecimalPlaces]
   * The amountDecimalPlaces property for the currency entity
   * @property {number}
   * [shippingPostalAddress.currency.amountRoundingPrecision] The
   * amountRoundingPrecision property for the currency entity
   * @property {date} [shippingPostalAddress.currency.lastModifiedDateTime] The
   * lastModifiedDateTime property for the currency entity
   * @property {object} [shippingPostalAddress.paymentTerm]
   * @property {uuid} [shippingPostalAddress.paymentTerm.id] The id property
   * for the paymentTerm entity
   * @property {string} [shippingPostalAddress.paymentTerm.code] The code
   * property for the paymentTerm entity
   * @property {string} [shippingPostalAddress.paymentTerm.displayName] The
   * displayName property for the paymentTerm entity
   * @property {string} [shippingPostalAddress.paymentTerm.dueDateCalculation]
   * The dueDateCalculation property for the paymentTerm entity
   * @property {string}
   * [shippingPostalAddress.paymentTerm.discountDateCalculation] The
   * discountDateCalculation property for the paymentTerm entity
   * @property {number} [shippingPostalAddress.paymentTerm.discountPercent] The
   * discountPercent property for the paymentTerm entity
   * @property {boolean}
   * [shippingPostalAddress.paymentTerm.calculateDiscountOnCreditMemos] The
   * calculateDiscountOnCreditMemos property for the paymentTerm entity
   * @property {date} [shippingPostalAddress.paymentTerm.lastModifiedDateTime]
   * The lastModifiedDateTime property for the paymentTerm entity
   * @property {object} [shippingPostalAddress.shipmentMethod]
   * @property {uuid} [shippingPostalAddress.shipmentMethod.id] The id property
   * for the shipmentMethod entity
   * @property {string} [shippingPostalAddress.shipmentMethod.code] The code
   * property for the shipmentMethod entity
   * @property {string} [shippingPostalAddress.shipmentMethod.displayName] The
   * displayName property for the shipmentMethod entity
   * @property {date}
   * [shippingPostalAddress.shipmentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the shipmentMethod entity
   * @property {object} [shippingPostalAddress.paymentMethod]
   * @property {uuid} [shippingPostalAddress.paymentMethod.id] The id property
   * for the paymentMethod entity
   * @property {string} [shippingPostalAddress.paymentMethod.code] The code
   * property for the paymentMethod entity
   * @property {string} [shippingPostalAddress.paymentMethod.displayName] The
   * displayName property for the paymentMethod entity
   * @property {date}
   * [shippingPostalAddress.paymentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentMethod entity
   * @property {uuid} [currencyId] The currencyId property for the salesInvoice
   * entity
   * @property {string} [currencyCode] The currencyCode property for the
   * salesInvoice entity
   * @property {uuid} [orderId] The orderId property for the salesInvoice
   * entity
   * @property {string} [orderNumber] The orderNumber property for the
   * salesInvoice entity
   * @property {uuid} [paymentTermsId] The paymentTermsId property for the
   * salesInvoice entity
   * @property {uuid} [shipmentMethodId] The shipmentMethodId property for the
   * salesInvoice entity
   * @property {string} [salesperson] The salesperson property for the
   * salesInvoice entity
   * @property {boolean} [pricesIncludeTax] The pricesIncludeTax property for
   * the salesInvoice entity
   * @property {number} [discountAmount] The discountAmount property for the
   * salesInvoice entity
   * @property {boolean} [discountAppliedBeforeTax] The
   * discountAppliedBeforeTax property for the salesInvoice entity
   * @property {number} [totalAmountExcludingTax] The totalAmountExcludingTax
   * property for the salesInvoice entity
   * @property {number} [totalTaxAmount] The totalTaxAmount property for the
   * salesInvoice entity
   * @property {number} [totalAmountIncludingTax] The totalAmountIncludingTax
   * property for the salesInvoice entity
   * @property {string} [status] The status property for the salesInvoice
   * entity
   * @property {date} [lastModifiedDateTime] The lastModifiedDateTime property
   * for the salesInvoice entity
   * @property {string} [phoneNumber] The phoneNumber property for the
   * salesInvoice entity
   * @property {string} [email] The email property for the salesInvoice entity
   * @property {array} [salesInvoiceLines]
   * @property {array} [pdfDocument]
   * @property {object} [customer]
   * @property {uuid} [customer.id] The id property for the customer entity
   * @property {string} [customer.number] The number property for the customer
   * entity
   * @property {string} [customer.displayName] The displayName property for the
   * customer entity
   * @property {string} [customer.type] The type property for the customer
   * entity
   * @property {object} [customer.address]
   * @property {string} [customer.address.street] The street property for the
   * postaladdresstype entity
   * @property {string} [customer.address.city] The city property for the
   * postaladdresstype entity
   * @property {string} [customer.address.state] The state property for the
   * postaladdresstype entity
   * @property {string} [customer.address.countryLetterCode] The
   * countryLetterCode property for the postaladdresstype entity
   * @property {string} [customer.address.postalCode] The postalCode property
   * for the postaladdresstype entity
   * @property {array} [customer.address.customerFinancialDetails]
   * @property {array} [customer.address.picture]
   * @property {array} [customer.address.defaultDimensions]
   * @property {object} [customer.address.currency]
   * @property {uuid} [customer.address.currency.id] The id property for the
   * currency entity
   * @property {string} [customer.address.currency.code] The code property for
   * the currency entity
   * @property {string} [customer.address.currency.displayName] The displayName
   * property for the currency entity
   * @property {string} [customer.address.currency.symbol] The symbol property
   * for the currency entity
   * @property {string} [customer.address.currency.amountDecimalPlaces] The
   * amountDecimalPlaces property for the currency entity
   * @property {number} [customer.address.currency.amountRoundingPrecision] The
   * amountRoundingPrecision property for the currency entity
   * @property {date} [customer.address.currency.lastModifiedDateTime] The
   * lastModifiedDateTime property for the currency entity
   * @property {object} [customer.address.paymentTerm]
   * @property {uuid} [customer.address.paymentTerm.id] The id property for the
   * paymentTerm entity
   * @property {string} [customer.address.paymentTerm.code] The code property
   * for the paymentTerm entity
   * @property {string} [customer.address.paymentTerm.displayName] The
   * displayName property for the paymentTerm entity
   * @property {string} [customer.address.paymentTerm.dueDateCalculation] The
   * dueDateCalculation property for the paymentTerm entity
   * @property {string} [customer.address.paymentTerm.discountDateCalculation]
   * The discountDateCalculation property for the paymentTerm entity
   * @property {number} [customer.address.paymentTerm.discountPercent] The
   * discountPercent property for the paymentTerm entity
   * @property {boolean}
   * [customer.address.paymentTerm.calculateDiscountOnCreditMemos] The
   * calculateDiscountOnCreditMemos property for the paymentTerm entity
   * @property {date} [customer.address.paymentTerm.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentTerm entity
   * @property {object} [customer.address.shipmentMethod]
   * @property {uuid} [customer.address.shipmentMethod.id] The id property for
   * the shipmentMethod entity
   * @property {string} [customer.address.shipmentMethod.code] The code
   * property for the shipmentMethod entity
   * @property {string} [customer.address.shipmentMethod.displayName] The
   * displayName property for the shipmentMethod entity
   * @property {date} [customer.address.shipmentMethod.lastModifiedDateTime]
   * The lastModifiedDateTime property for the shipmentMethod entity
   * @property {object} [customer.address.paymentMethod]
   * @property {uuid} [customer.address.paymentMethod.id] The id property for
   * the paymentMethod entity
   * @property {string} [customer.address.paymentMethod.code] The code property
   * for the paymentMethod entity
   * @property {string} [customer.address.paymentMethod.displayName] The
   * displayName property for the paymentMethod entity
   * @property {date} [customer.address.paymentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentMethod entity
   * @property {string} [customer.phoneNumber] The phoneNumber property for the
   * customer entity
   * @property {string} [customer.email] The email property for the customer
   * entity
   * @property {string} [customer.website] The website property for the
   * customer entity
   * @property {boolean} [customer.taxLiable] The taxLiable property for the
   * customer entity
   * @property {uuid} [customer.taxAreaId] The taxAreaId property for the
   * customer entity
   * @property {string} [customer.taxAreaDisplayName] The taxAreaDisplayName
   * property for the customer entity
   * @property {string} [customer.taxRegistrationNumber] The
   * taxRegistrationNumber property for the customer entity
   * @property {uuid} [customer.currencyId] The currencyId property for the
   * customer entity
   * @property {string} [customer.currencyCode] The currencyCode property for
   * the customer entity
   * @property {uuid} [customer.paymentTermsId] The paymentTermsId property for
   * the customer entity
   * @property {uuid} [customer.shipmentMethodId] The shipmentMethodId property
   * for the customer entity
   * @property {uuid} [customer.paymentMethodId] The paymentMethodId property
   * for the customer entity
   * @property {string} [customer.blocked] The blocked property for the
   * customer entity
   * @property {date} [customer.lastModifiedDateTime] The lastModifiedDateTime
   * property for the customer entity
   * @property {array} [customer.customerFinancialDetails]
   * @property {array} [customer.picture]
   * @property {array} [customer.defaultDimensions]
   * @property {object} [customer.currency]
   * @property {uuid} [customer.currency.id] The id property for the currency
   * entity
   * @property {string} [customer.currency.code] The code property for the
   * currency entity
   * @property {string} [customer.currency.displayName] The displayName
   * property for the currency entity
   * @property {string} [customer.currency.symbol] The symbol property for the
   * currency entity
   * @property {string} [customer.currency.amountDecimalPlaces] The
   * amountDecimalPlaces property for the currency entity
   * @property {number} [customer.currency.amountRoundingPrecision] The
   * amountRoundingPrecision property for the currency entity
   * @property {date} [customer.currency.lastModifiedDateTime] The
   * lastModifiedDateTime property for the currency entity
   * @property {object} [customer.paymentTerm]
   * @property {uuid} [customer.paymentTerm.id] The id property for the
   * paymentTerm entity
   * @property {string} [customer.paymentTerm.code] The code property for the
   * paymentTerm entity
   * @property {string} [customer.paymentTerm.displayName] The displayName
   * property for the paymentTerm entity
   * @property {string} [customer.paymentTerm.dueDateCalculation] The
   * dueDateCalculation property for the paymentTerm entity
   * @property {string} [customer.paymentTerm.discountDateCalculation] The
   * discountDateCalculation property for the paymentTerm entity
   * @property {number} [customer.paymentTerm.discountPercent] The
   * discountPercent property for the paymentTerm entity
   * @property {boolean} [customer.paymentTerm.calculateDiscountOnCreditMemos]
   * The calculateDiscountOnCreditMemos property for the paymentTerm entity
   * @property {date} [customer.paymentTerm.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentTerm entity
   * @property {object} [customer.shipmentMethod]
   * @property {uuid} [customer.shipmentMethod.id] The id property for the
   * shipmentMethod entity
   * @property {string} [customer.shipmentMethod.code] The code property for
   * the shipmentMethod entity
   * @property {string} [customer.shipmentMethod.displayName] The displayName
   * property for the shipmentMethod entity
   * @property {date} [customer.shipmentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the shipmentMethod entity
   * @property {object} [customer.paymentMethod]
   * @property {uuid} [customer.paymentMethod.id] The id property for the
   * paymentMethod entity
   * @property {string} [customer.paymentMethod.code] The code property for the
   * paymentMethod entity
   * @property {string} [customer.paymentMethod.displayName] The displayName
   * property for the paymentMethod entity
   * @property {date} [customer.paymentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentMethod entity
   * @property {object} [currency]
   * @property {uuid} [currency.id] The id property for the currency entity
   * @property {string} [currency.code] The code property for the currency
   * entity
   * @property {string} [currency.displayName] The displayName property for the
   * currency entity
   * @property {string} [currency.symbol] The symbol property for the currency
   * entity
   * @property {string} [currency.amountDecimalPlaces] The amountDecimalPlaces
   * property for the currency entity
   * @property {number} [currency.amountRoundingPrecision] The
   * amountRoundingPrecision property for the currency entity
   * @property {date} [currency.lastModifiedDateTime] The lastModifiedDateTime
   * property for the currency entity
   * @property {object} [paymentTerm]
   * @property {uuid} [paymentTerm.id] The id property for the paymentTerm
   * entity
   * @property {string} [paymentTerm.code] The code property for the
   * paymentTerm entity
   * @property {string} [paymentTerm.displayName] The displayName property for
   * the paymentTerm entity
   * @property {string} [paymentTerm.dueDateCalculation] The dueDateCalculation
   * property for the paymentTerm entity
   * @property {string} [paymentTerm.discountDateCalculation] The
   * discountDateCalculation property for the paymentTerm entity
   * @property {number} [paymentTerm.discountPercent] The discountPercent
   * property for the paymentTerm entity
   * @property {boolean} [paymentTerm.calculateDiscountOnCreditMemos] The
   * calculateDiscountOnCreditMemos property for the paymentTerm entity
   * @property {date} [paymentTerm.lastModifiedDateTime] The
   * lastModifiedDateTime property for the paymentTerm entity
   * @property {object} [shipmentMethod]
   * @property {uuid} [shipmentMethod.id] The id property for the
   * shipmentMethod entity
   * @property {string} [shipmentMethod.code] The code property for the
   * shipmentMethod entity
   * @property {string} [shipmentMethod.displayName] The displayName property
   * for the shipmentMethod entity
   * @property {date} [shipmentMethod.lastModifiedDateTime] The
   * lastModifiedDateTime property for the shipmentMethod entity
   */
  constructor() {
  }

  /**
   * Defines the metadata of SalesInvoice
   *
   * @returns {object} metadata of SalesInvoice
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'salesInvoice',
      type: {
        name: 'Composite',
        className: 'SalesInvoice',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          number: {
            required: false,
            serializedName: 'number',
            constraints: {
              MaxLength: 20
            },
            type: {
              name: 'String'
            }
          },
          externalDocumentNumber: {
            required: false,
            serializedName: 'externalDocumentNumber',
            constraints: {
              MaxLength: 35
            },
            type: {
              name: 'String'
            }
          },
          invoiceDate: {
            required: false,
            serializedName: 'invoiceDate',
            type: {
              name: 'DateTime'
            }
          },
          dueDate: {
            required: false,
            serializedName: 'dueDate',
            type: {
              name: 'DateTime'
            }
          },
          customerPurchaseOrderReference: {
            required: false,
            serializedName: 'customerPurchaseOrderReference',
            constraints: {
              MaxLength: 35
            },
            type: {
              name: 'String'
            }
          },
          customerId: {
            required: false,
            serializedName: 'customerId',
            type: {
              name: 'String'
            }
          },
          contactId: {
            required: false,
            serializedName: 'contactId',
            constraints: {
              MaxLength: 250
            },
            type: {
              name: 'String'
            }
          },
          customerNumber: {
            required: false,
            serializedName: 'customerNumber',
            constraints: {
              MaxLength: 20
            },
            type: {
              name: 'String'
            }
          },
          customerName: {
            required: false,
            serializedName: 'customerName',
            constraints: {
              MaxLength: 100
            },
            type: {
              name: 'String'
            }
          },
          billToName: {
            required: false,
            serializedName: 'billToName',
            constraints: {
              MaxLength: 100
            },
            type: {
              name: 'String'
            }
          },
          billToCustomerId: {
            required: false,
            serializedName: 'billToCustomerId',
            type: {
              name: 'String'
            }
          },
          billToCustomerNumber: {
            required: false,
            serializedName: 'billToCustomerNumber',
            constraints: {
              MaxLength: 20
            },
            type: {
              name: 'String'
            }
          },
          shipToName: {
            required: false,
            serializedName: 'shipToName',
            constraints: {
              MaxLength: 100
            },
            type: {
              name: 'String'
            }
          },
          shipToContact: {
            required: false,
            serializedName: 'shipToContact',
            constraints: {
              MaxLength: 100
            },
            type: {
              name: 'String'
            }
          },
          sellingPostalAddress: {
            required: false,
            serializedName: 'sellingPostalAddress',
            type: {
              name: 'Composite',
              className: 'Postaladdresstype'
            }
          },
          billingPostalAddress: {
            required: false,
            serializedName: 'billingPostalAddress',
            type: {
              name: 'Composite',
              className: 'Postaladdresstype'
            }
          },
          shippingPostalAddress: {
            required: false,
            serializedName: 'shippingPostalAddress',
            type: {
              name: 'Composite',
              className: 'Postaladdresstype'
            }
          },
          currencyId: {
            required: false,
            serializedName: 'currencyId',
            type: {
              name: 'String'
            }
          },
          currencyCode: {
            required: false,
            serializedName: 'currencyCode',
            type: {
              name: 'String'
            }
          },
          orderId: {
            required: false,
            serializedName: 'orderId',
            type: {
              name: 'String'
            }
          },
          orderNumber: {
            required: false,
            serializedName: 'orderNumber',
            constraints: {
              MaxLength: 20
            },
            type: {
              name: 'String'
            }
          },
          paymentTermsId: {
            required: false,
            serializedName: 'paymentTermsId',
            type: {
              name: 'String'
            }
          },
          shipmentMethodId: {
            required: false,
            serializedName: 'shipmentMethodId',
            type: {
              name: 'String'
            }
          },
          salesperson: {
            required: false,
            serializedName: 'salesperson',
            constraints: {
              MaxLength: 20
            },
            type: {
              name: 'String'
            }
          },
          pricesIncludeTax: {
            required: false,
            serializedName: 'pricesIncludeTax',
            type: {
              name: 'Boolean'
            }
          },
          discountAmount: {
            required: false,
            serializedName: 'discountAmount',
            type: {
              name: 'Number'
            }
          },
          discountAppliedBeforeTax: {
            required: false,
            serializedName: 'discountAppliedBeforeTax',
            type: {
              name: 'Boolean'
            }
          },
          totalAmountExcludingTax: {
            required: false,
            serializedName: 'totalAmountExcludingTax',
            type: {
              name: 'Number'
            }
          },
          totalTaxAmount: {
            required: false,
            serializedName: 'totalTaxAmount',
            type: {
              name: 'Number'
            }
          },
          totalAmountIncludingTax: {
            required: false,
            serializedName: 'totalAmountIncludingTax',
            type: {
              name: 'Number'
            }
          },
          status: {
            required: false,
            serializedName: 'status',
            type: {
              name: 'String'
            }
          },
          lastModifiedDateTime: {
            required: false,
            serializedName: 'lastModifiedDateTime',
            type: {
              name: 'DateTime'
            }
          },
          phoneNumber: {
            required: false,
            serializedName: 'phoneNumber',
            constraints: {
              MaxLength: 30
            },
            type: {
              name: 'String'
            }
          },
          email: {
            required: false,
            serializedName: 'email',
            constraints: {
              MaxLength: 80
            },
            type: {
              name: 'String'
            }
          },
          salesInvoiceLines: {
            required: false,
            serializedName: 'salesInvoiceLines',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'SalesInvoiceLineElementType',
                  type: {
                    name: 'Composite',
                    className: 'SalesInvoiceLine'
                  }
              }
            }
          },
          pdfDocument: {
            required: false,
            serializedName: 'pdfDocument',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'PdfDocumentElementType',
                  type: {
                    name: 'Composite',
                    className: 'PdfDocument'
                  }
              }
            }
          },
          customer: {
            required: false,
            serializedName: 'customer',
            type: {
              name: 'Composite',
              className: 'Customer'
            }
          },
          currency: {
            required: false,
            serializedName: 'currency',
            type: {
              name: 'Composite',
              className: 'Currency'
            }
          },
          paymentTerm: {
            required: false,
            serializedName: 'paymentTerm',
            type: {
              name: 'Composite',
              className: 'PaymentTerm'
            }
          },
          shipmentMethod: {
            required: false,
            serializedName: 'shipmentMethod',
            type: {
              name: 'Composite',
              className: 'ShipmentMethod'
            }
          }
        }
      }
    };
  }
}

module.exports = SalesInvoice;
