/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The metric dimension name and value.
 *
 */
class MetricSingleDimension {
  /**
   * Create a MetricSingleDimension.
   * @property {string} name Name of the dimension.
   * @property {string} value Value of the dimension.
   */
  constructor() {
  }

  /**
   * Defines the metadata of MetricSingleDimension
   *
   * @returns {object} metadata of MetricSingleDimension
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'MetricSingleDimension',
      type: {
        name: 'Composite',
        className: 'MetricSingleDimension',
        modelProperties: {
          name: {
            required: true,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          value: {
            required: true,
            serializedName: 'value',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = MetricSingleDimension;
