/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The types of conditions for a multi resource alert.
 *
 */
class MultiMetricCriteria {
  /**
   * Create a MultiMetricCriteria.
   * @property {string} name Name of the criteria.
   * @property {string} metricName Name of the metric.
   * @property {string} [metricNamespace] Namespace of the metric.
   * @property {object} timeAggregation the criteria time aggregation types.
   * @property {array} [dimensions] List of dimension conditions.
   * @property {string} criterionType Polymorphic Discriminator
   */
  constructor() {
  }

  /**
   * Defines the metadata of MultiMetricCriteria
   *
   * @returns {object} metadata of MultiMetricCriteria
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'MultiMetricCriteria',
      type: {
        name: 'Composite',
        additionalProperties: {
          type: {
            name: 'Dictionary',
            value: {
                required: false,
                serializedName: 'ObjectElementType',
                type: {
                  name: 'Object'
                }
            }
          }
        },
        polymorphicDiscriminator: {
          serializedName: 'criterionType',
          clientName: 'criterionType'
        },
        uberParent: 'MultiMetricCriteria',
        className: 'MultiMetricCriteria',
        modelProperties: {
          name: {
            required: true,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          metricName: {
            required: true,
            serializedName: 'metricName',
            type: {
              name: 'String'
            }
          },
          metricNamespace: {
            required: false,
            serializedName: 'metricNamespace',
            type: {
              name: 'String'
            }
          },
          timeAggregation: {
            required: true,
            serializedName: 'timeAggregation',
            type: {
              name: 'Object'
            }
          },
          dimensions: {
            required: false,
            serializedName: 'dimensions',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'MetricDimensionElementType',
                  type: {
                    name: 'Composite',
                    className: 'MetricDimension'
                  }
              }
            }
          },
          criterionType: {
            required: true,
            serializedName: 'criterionType',
            isPolymorphicDiscriminator: true,
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = MultiMetricCriteria;
