/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Defines the parameters for RemoteAddress match conditions
 *
 */
class RemoteAddressMatchConditionParameters {
  /**
   * Create a RemoteAddressMatchConditionParameters.
   * @property {string} operator Describes operator to be matched. Possible
   * values include: 'Any', 'IPMatch', 'GeoMatch'
   * @property {boolean} [negateCondition] Describes if this is negate
   * condition or not
   * @property {array} matchValues Match values to match against. The operator
   * will apply to each value in here with OR semantics. If any of them match
   * the variable with the given operator this match condition is considered a
   * match.
   * @property {array} [transforms] List of transforms
   */
  constructor() {
  }

  /**
   * Defines the metadata of RemoteAddressMatchConditionParameters
   *
   * @returns {object} metadata of RemoteAddressMatchConditionParameters
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'RemoteAddressMatchConditionParameters',
      type: {
        name: 'Composite',
        className: 'RemoteAddressMatchConditionParameters',
        modelProperties: {
          odatatype: {
            required: true,
            isConstant: true,
            serializedName: '@odata\\.type',
            defaultValue: '#Microsoft.Azure.Cdn.Models.DeliveryRuleRemoteAddressConditionParameters',
            type: {
              name: 'String'
            }
          },
          operator: {
            required: true,
            serializedName: 'operator',
            type: {
              name: 'String'
            }
          },
          negateCondition: {
            required: false,
            serializedName: 'negateCondition',
            type: {
              name: 'Boolean'
            }
          },
          matchValues: {
            required: true,
            serializedName: 'matchValues',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          transforms: {
            required: false,
            serializedName: 'transforms',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'TransformElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = RemoteAddressMatchConditionParameters;
