/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Defines the parameters for RequestHeader match conditions
 *
 */
class RequestHeaderMatchConditionParameters {
  /**
   * Create a RequestHeaderMatchConditionParameters.
   * @property {string} selector Name of Header to be matched
   * @property {string} operator Describes operator to be matched. Possible
   * values include: 'Any', 'Equal', 'Contains', 'BeginsWith', 'EndsWith',
   * 'LessThan', 'LessThanOrEqual', 'GreaterThan', 'GreaterThanOrEqual'
   * @property {boolean} [negateCondition] Describes if this is negate
   * condition or not
   * @property {array} matchValues The match value for the condition of the
   * delivery rule
   * @property {array} [transforms] List of transforms
   */
  constructor() {
  }

  /**
   * Defines the metadata of RequestHeaderMatchConditionParameters
   *
   * @returns {object} metadata of RequestHeaderMatchConditionParameters
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'RequestHeaderMatchConditionParameters',
      type: {
        name: 'Composite',
        className: 'RequestHeaderMatchConditionParameters',
        modelProperties: {
          odatatype: {
            required: true,
            isConstant: true,
            serializedName: '@odata\\.type',
            defaultValue: '#Microsoft.Azure.Cdn.Models.DeliveryRuleRequestHeaderConditionParameters',
            type: {
              name: 'String'
            }
          },
          selector: {
            required: true,
            serializedName: 'selector',
            type: {
              name: 'String'
            }
          },
          operator: {
            required: true,
            serializedName: 'operator',
            type: {
              name: 'String'
            }
          },
          negateCondition: {
            required: false,
            serializedName: 'negateCondition',
            type: {
              name: 'Boolean'
            }
          },
          matchValues: {
            required: true,
            serializedName: 'matchValues',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          transforms: {
            required: false,
            serializedName: 'transforms',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'TransformElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = RequestHeaderMatchConditionParameters;
