/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Contains prev and next reservation Ids' because of renewal.
 *
 */
class RenewPropertiesResponseLinks {
  /**
   * Create a RenewPropertiesResponseLinks.
   * @property {string} [renewSource] Reservation Id of the reservation from
   * which this reservation is renewed. Format of the resource Id is
   * /providers/Microsoft.Capacity/reservationOrders/{reservationOrderId}/reservations/{reservationId}.
   * @property {string} [renewDestination] Reservation Id of the reservation
   * which is purchased because of renew. Format of the resource Id is
   * /providers/Microsoft.Capacity/reservationOrders/{reservationOrderId}/reservations/{reservationId}.
   */
  constructor() {
  }

  /**
   * Defines the metadata of RenewPropertiesResponseLinks
   *
   * @returns {object} metadata of RenewPropertiesResponseLinks
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'RenewPropertiesResponse_links',
      type: {
        name: 'Composite',
        className: 'RenewPropertiesResponseLinks',
        modelProperties: {
          renewSource: {
            required: false,
            serializedName: 'renewSource',
            type: {
              name: 'String'
            }
          },
          renewDestination: {
            required: false,
            serializedName: 'renewDestination',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = RenewPropertiesResponseLinks;
