/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Locked currency & amount for new reservation purchase at the time of
 * renewal. Price is locked 30 days before expiry date time if renew is true.
 *
 */
class RenewPropertiesResponseLockedPriceTotal {
  /**
   * Create a RenewPropertiesResponseLockedPriceTotal.
   * @property {string} [currencyCode]
   * @property {string} [amount]
   */
  constructor() {
  }

  /**
   * Defines the metadata of RenewPropertiesResponseLockedPriceTotal
   *
   * @returns {object} metadata of RenewPropertiesResponseLockedPriceTotal
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'RenewPropertiesResponse_lockedPriceTotal',
      type: {
        name: 'Composite',
        className: 'RenewPropertiesResponseLockedPriceTotal',
        modelProperties: {
          currencyCode: {
            required: false,
            serializedName: 'currencyCode',
            type: {
              name: 'String'
            }
          },
          amount: {
            required: false,
            serializedName: 'amount',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = RenewPropertiesResponseLockedPriceTotal;
