/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The policies for a container registry.
 *
 */
class Policies {
  /**
   * Create a Policies.
   * @property {object} [quarantinePolicy] The quarantine policy for a
   * container registry.
   * @property {string} [quarantinePolicy.status] The value that indicates
   * whether the policy is enabled or not. Possible values include: 'enabled',
   * 'disabled'
   * @property {object} [trustPolicy] The content trust policy for a container
   * registry.
   * @property {string} [trustPolicy.type] The type of trust policy. Possible
   * values include: 'Notary'
   * @property {string} [trustPolicy.status] The value that indicates whether
   * the policy is enabled or not. Possible values include: 'enabled',
   * 'disabled'
   * @property {object} [retentionPolicy] The retention policy for a container
   * registry.
   * @property {number} [retentionPolicy.days] The number of days to retain
   * manifest before it expires.
   * @property {date} [retentionPolicy.lastUpdatedTime] The timestamp when the
   * policy was last updated.
   * @property {string} [retentionPolicy.status] The value that indicates
   * whether the policy is enabled or not. Possible values include: 'enabled',
   * 'disabled'
   */
  constructor() {
  }

  /**
   * Defines the metadata of Policies
   *
   * @returns {object} metadata of Policies
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Policies',
      type: {
        name: 'Composite',
        className: 'Policies',
        modelProperties: {
          quarantinePolicy: {
            required: false,
            serializedName: 'quarantinePolicy',
            type: {
              name: 'Composite',
              className: 'QuarantinePolicy'
            }
          },
          trustPolicy: {
            required: false,
            serializedName: 'trustPolicy',
            type: {
              name: 'Composite',
              className: 'TrustPolicy'
            }
          },
          retentionPolicy: {
            required: false,
            serializedName: 'retentionPolicy',
            type: {
              name: 'Composite',
              className: 'RetentionPolicy'
            }
          }
        }
      }
    };
  }
}

module.exports = Policies;
