/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The result of a request to list scope maps for a container registry.
 */
class ScopeMapListResult extends Array {
  /**
   * Create a ScopeMapListResult.
   * @property {string} [nextLink] The URI that can be used to request the next
   * list of scope maps.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of ScopeMapListResult
   *
   * @returns {object} metadata of ScopeMapListResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ScopeMapListResult',
      type: {
        name: 'Composite',
        className: 'ScopeMapListResult',
        modelProperties: {
          value: {
            required: false,
            serializedName: '',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ScopeMapElementType',
                  type: {
                    name: 'Composite',
                    className: 'ScopeMap'
                  }
              }
            }
          },
          nextLink: {
            required: false,
            serializedName: 'nextLink',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ScopeMapListResult;
