/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * A billing profile resource.
 *
 * @extends models['Resource']
 */
class BillingProfile extends models['Resource'] {
  /**
   * Create a BillingProfile.
   * @property {string} [displayName] The billing profile name.
   * @property {string} [poNumber] Purchase order number.
   * @property {object} [address] Billing address.
   * @property {string} [address.firstName] First Name.
   * @property {string} [address.lastName] Last Name.
   * @property {string} [address.companyName] Company Name.
   * @property {string} [address.addressLine1] Address Line1.
   * @property {string} [address.addressLine2] Address Line2.
   * @property {string} [address.addressLine3] Address Line3.
   * @property {string} [address.city] Address City.
   * @property {string} [address.region] Address Region.
   * @property {string} [address.country] Country code uses ISO2, 2-digit
   * format.
   * @property {string} [address.postalCode] Address Postal Code.
   * @property {boolean} [invoiceEmailOptIn] If the billing profile is opted in
   * to receive invoices via email.
   * @property {boolean} [isClassic] Is OMS bootstrapped billing profile.
   * @property {number} [invoiceDay] Invoice day.
   * @property {string} [currency] The currency associated with the billing
   * profile.
   * @property {array} [enabledAzureSKUs] Information about the product.
   * @property {array} [invoiceSections] The invoice sections associated to the
   * billing profile.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of BillingProfile
   *
   * @returns {object} metadata of BillingProfile
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'BillingProfile',
      type: {
        name: 'Composite',
        className: 'BillingProfile',
        modelProperties: {
          id: {
            required: false,
            readOnly: true,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            readOnly: true,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            readOnly: true,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          displayName: {
            required: false,
            serializedName: 'properties.displayName',
            type: {
              name: 'String'
            }
          },
          poNumber: {
            required: false,
            serializedName: 'properties.poNumber',
            type: {
              name: 'String'
            }
          },
          address: {
            required: false,
            serializedName: 'properties.address',
            type: {
              name: 'Composite',
              className: 'Address'
            }
          },
          invoiceEmailOptIn: {
            required: false,
            readOnly: true,
            serializedName: 'properties.invoiceEmailOptIn',
            type: {
              name: 'Boolean'
            }
          },
          isClassic: {
            required: false,
            readOnly: true,
            serializedName: 'properties.isClassic',
            type: {
              name: 'Boolean'
            }
          },
          invoiceDay: {
            required: false,
            readOnly: true,
            serializedName: 'properties.invoiceDay',
            type: {
              name: 'Number'
            }
          },
          currency: {
            required: false,
            readOnly: true,
            serializedName: 'properties.currency',
            type: {
              name: 'String'
            }
          },
          enabledAzureSKUs: {
            required: false,
            serializedName: 'properties.enabledAzureSKUs',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'EnabledAzureSKUsElementType',
                  type: {
                    name: 'Composite',
                    className: 'EnabledAzureSKUs'
                  }
              }
            }
          },
          invoiceSections: {
            required: false,
            serializedName: 'properties.invoiceSections',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'InvoiceSectionElementType',
                  type: {
                    name: 'Composite',
                    className: 'InvoiceSection'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = BillingProfile;
