/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Error details of the transfer eligibility validation
 *
 */
class ValidateSubscriptionTransferEligibilityError {
  /**
   * Create a ValidateSubscriptionTransferEligibilityError.
   * @property {string} [code] Error code for the product transfer validation.
   * Possible values include: 'InvalidSource', 'SubscriptionNotActive',
   * 'InsufficientPermissionOnSource', 'InsufficientPermissionOnDestination',
   * 'DestinationBillingProfilePastDue', 'SubscriptionTypeNotSupported',
   * 'CrossBillingAccountNotAllowed', 'NotAvailableForDestinationMarket'
   * @property {string} [message] The error message.
   * @property {string} [details] Detailed error message explaining the error.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ValidateSubscriptionTransferEligibilityError
   *
   * @returns {object} metadata of ValidateSubscriptionTransferEligibilityError
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ValidateSubscriptionTransferEligibilityError',
      type: {
        name: 'Composite',
        className: 'ValidateSubscriptionTransferEligibilityError',
        modelProperties: {
          code: {
            required: false,
            serializedName: 'code',
            type: {
              name: 'String'
            }
          },
          message: {
            required: false,
            serializedName: 'message',
            type: {
              name: 'String'
            }
          },
          details: {
            required: false,
            serializedName: 'details',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ValidateSubscriptionTransferEligibilityError;
