/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Cosmos DB Cassandra table id object
 *
 */
class CassandraTableResource {
  /**
   * Create a CassandraTableResource.
   * @property {string} id Name of the Cosmos DB Cassandra table
   * @property {number} [defaultTtl] Time to live of the Cosmos DB Cassandra
   * table
   * @property {object} [schema] Schema of the Cosmos DB Cassandra table
   * @property {array} [schema.columns] List of Cassandra table columns.
   * @property {array} [schema.partitionKeys] List of partition key.
   * @property {array} [schema.clusterKeys] List of cluster key.
   */
  constructor() {
  }

  /**
   * Defines the metadata of CassandraTableResource
   *
   * @returns {object} metadata of CassandraTableResource
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'CassandraTableResource',
      type: {
        name: 'Composite',
        className: 'CassandraTableResource',
        modelProperties: {
          id: {
            required: true,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          defaultTtl: {
            required: false,
            serializedName: 'defaultTtl',
            type: {
              name: 'Number'
            }
          },
          schema: {
            required: false,
            serializedName: 'schema',
            type: {
              name: 'Composite',
              className: 'CassandraSchema'
            }
          }
        }
      }
    };
  }
}

module.exports = CassandraTableResource;
