/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Cosmos DB Cassandra table schema
 *
 */
class CassandraSchema {
  /**
   * Create a CassandraSchema.
   * @property {array} [columns] List of Cassandra table columns.
   * @property {array} [partitionKeys] List of partition key.
   * @property {array} [clusterKeys] List of cluster key.
   */
  constructor() {
  }

  /**
   * Defines the metadata of CassandraSchema
   *
   * @returns {object} metadata of CassandraSchema
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'CassandraSchema',
      type: {
        name: 'Composite',
        className: 'CassandraSchema',
        modelProperties: {
          columns: {
            required: false,
            serializedName: 'columns',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ColumnElementType',
                  type: {
                    name: 'Composite',
                    className: 'Column'
                  }
              }
            }
          },
          partitionKeys: {
            required: false,
            serializedName: 'partitionKeys',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CassandraPartitionKeyElementType',
                  type: {
                    name: 'Composite',
                    className: 'CassandraPartitionKey'
                  }
              }
            }
          },
          clusterKeys: {
            required: false,
            serializedName: 'clusterKeys',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ClusterKeyElementType',
                  type: {
                    name: 'Composite',
                    className: 'ClusterKey'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = CassandraSchema;
