/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * An Azure Cosmos DB Cassandra table.
 *
 * @extends models['Resource']
 */
class CassandraTable extends models['Resource'] {
  /**
   * Create a CassandraTable.
   * @property {string} cassandraTableId Name of the Cosmos DB Cassandra table
   * @property {number} [defaultTtl] Time to live of the Cosmos DB Cassandra
   * table
   * @property {object} [schema] Schema of the Cosmos DB Cassandra table
   * @property {array} [schema.columns] List of Cassandra table columns.
   * @property {array} [schema.partitionKeys] List of partition key.
   * @property {array} [schema.clusterKeys] List of cluster key.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of CassandraTable
   *
   * @returns {object} metadata of CassandraTable
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'CassandraTable',
      type: {
        name: 'Composite',
        className: 'CassandraTable',
        modelProperties: {
          id: {
            required: false,
            readOnly: true,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            readOnly: true,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            readOnly: true,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          location: {
            required: false,
            serializedName: 'location',
            type: {
              name: 'String'
            }
          },
          tags: {
            required: false,
            serializedName: 'tags',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          cassandraTableId: {
            required: true,
            serializedName: 'properties.id',
            type: {
              name: 'String'
            }
          },
          defaultTtl: {
            required: false,
            serializedName: 'properties.defaultTtl',
            type: {
              name: 'Number'
            }
          },
          schema: {
            required: false,
            serializedName: 'properties.schema',
            type: {
              name: 'Composite',
              className: 'CassandraSchema'
            }
          }
        }
      }
    };
  }
}

module.exports = CassandraTable;
