/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The List operation response, that contains the Cassandra tables and their
 * properties.
 */
class CassandraTableListResult extends Array {
  /**
   * Create a CassandraTableListResult.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of CassandraTableListResult
   *
   * @returns {object} metadata of CassandraTableListResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'CassandraTableListResult',
      type: {
        name: 'Composite',
        className: 'CassandraTableListResult',
        modelProperties: {
          value: {
            required: false,
            readOnly: true,
            serializedName: '',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CassandraTableElementType',
                  type: {
                    name: 'Composite',
                    className: 'CassandraTable'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = CassandraTableListResult;
