/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The conflict resolution policy for the container.
 *
 */
class ConflictResolutionPolicy {
  /**
   * Create a ConflictResolutionPolicy.
   * @property {string} [mode] Indicates the conflict resolution mode. Possible
   * values include: 'LastWriterWins', 'Custom'. Default value:
   * 'LastWriterWins' .
   * @property {string} [conflictResolutionPath] The conflict resolution path
   * in the case of LastWriterWins mode.
   * @property {string} [conflictResolutionProcedure] The procedure to resolve
   * conflicts in the case of custom mode.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ConflictResolutionPolicy
   *
   * @returns {object} metadata of ConflictResolutionPolicy
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ConflictResolutionPolicy',
      type: {
        name: 'Composite',
        className: 'ConflictResolutionPolicy',
        modelProperties: {
          mode: {
            required: false,
            serializedName: 'mode',
            defaultValue: 'LastWriterWins',
            type: {
              name: 'String'
            }
          },
          conflictResolutionPath: {
            required: false,
            serializedName: 'conflictResolutionPath',
            type: {
              name: 'String'
            }
          },
          conflictResolutionProcedure: {
            required: false,
            serializedName: 'conflictResolutionProcedure',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ConflictResolutionPolicy;
