/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a ExcludedPath.
 */
class ExcludedPath {
  /**
   * Create a ExcludedPath.
   * @property {string} [path] The path for which the indexing behavior applies
   * to. Index paths typically start with root and end with wildcard (/path/*)
   */
  constructor() {
  }

  /**
   * Defines the metadata of ExcludedPath
   *
   * @returns {object} metadata of ExcludedPath
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ExcludedPath',
      type: {
        name: 'Composite',
        className: 'ExcludedPath',
        modelProperties: {
          path: {
            required: false,
            serializedName: 'path',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ExcludedPath;
