/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The system generated resource properties associated with SQL databases and
 * SQL containers.
 *
 */
class ExtendedResourceProperties {
  /**
   * Create a ExtendedResourceProperties.
   * @property {string} [_rid] A system generated property. A unique
   * identifier.
   * @property {object} [_ts] A system generated property that denotes the last
   * updated timestamp of the resource.
   * @property {string} [_etag] A system generated property representing the
   * resource etag required for optimistic concurrency control.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ExtendedResourceProperties
   *
   * @returns {object} metadata of ExtendedResourceProperties
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ExtendedResourceProperties',
      type: {
        name: 'Composite',
        className: 'ExtendedResourceProperties',
        modelProperties: {
          _rid: {
            required: false,
            serializedName: '_rid',
            type: {
              name: 'String'
            }
          },
          _ts: {
            required: false,
            serializedName: '_ts',
            type: {
              name: 'Object'
            }
          },
          _etag: {
            required: false,
            serializedName: '_etag',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ExtendedResourceProperties;
