/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The indexes for the path.
 *
 */
class Indexes {
  /**
   * Create a Indexes.
   * @property {string} [dataType] The datatype for which the indexing behavior
   * is applied to. Possible values include: 'String', 'Number', 'Point',
   * 'Polygon', 'LineString', 'MultiPolygon'. Default value: 'String' .
   * @property {number} [precision] The precision of the index. -1 is maximum
   * precision.
   * @property {string} [kind] Indicates the type of index. Possible values
   * include: 'Hash', 'Range', 'Spatial'. Default value: 'Hash' .
   */
  constructor() {
  }

  /**
   * Defines the metadata of Indexes
   *
   * @returns {object} metadata of Indexes
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Indexes',
      type: {
        name: 'Composite',
        className: 'Indexes',
        modelProperties: {
          dataType: {
            required: false,
            serializedName: 'dataType',
            defaultValue: 'String',
            type: {
              name: 'String'
            }
          },
          precision: {
            required: false,
            serializedName: 'precision',
            type: {
              name: 'Number'
            }
          },
          kind: {
            required: false,
            serializedName: 'kind',
            defaultValue: 'Hash',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Indexes;
