/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

var msRestAzure = require('ms-rest-azure');

exports.BaseResource = msRestAzure.BaseResource;
exports.CloudError = msRestAzure.CloudError;
exports.ConsistencyPolicy = require('./consistencyPolicy');
exports.Capability = require('./capability');
exports.Location = require('./location');
exports.FailoverPolicy = require('./failoverPolicy');
exports.VirtualNetworkRule = require('./virtualNetworkRule');
exports.Resource = require('./resource');
exports.DatabaseAccount = require('./databaseAccount');
exports.SqlDatabase = require('./sqlDatabase');
exports.Indexes = require('./indexes');
exports.IncludedPath = require('./includedPath');
exports.ExcludedPath = require('./excludedPath');
exports.IndexingPolicy = require('./indexingPolicy');
exports.ContainerPartitionKey = require('./containerPartitionKey');
exports.UniqueKey = require('./uniqueKey');
exports.UniqueKeyPolicy = require('./uniqueKeyPolicy');
exports.ConflictResolutionPolicy = require('./conflictResolutionPolicy');
exports.Container = require('./container');
exports.MongoDatabase = require('./mongoDatabase');
exports.MongoCollection = require('./mongoCollection');
exports.Table = require('./table');
exports.CassandraKeyspace = require('./cassandraKeyspace');
exports.CassandraTable = require('./cassandraTable');
exports.GremlinDatabase = require('./gremlinDatabase');
exports.ErrorResponse = require('./errorResponse');
exports.FailoverPolicies = require('./failoverPolicies');
exports.RegionForOnlineOffline = require('./regionForOnlineOffline');
exports.ExtendedResourceProperties = require('./extendedResourceProperties');
exports.DatabaseAccountCreateUpdateParameters = require('./databaseAccountCreateUpdateParameters');
exports.DatabaseAccountPatchParameters = require('./databaseAccountPatchParameters');
exports.DatabaseAccountListReadOnlyKeysResult = require('./databaseAccountListReadOnlyKeysResult');
exports.DatabaseAccountListKeysResult = require('./databaseAccountListKeysResult');
exports.DatabaseAccountConnectionString = require('./databaseAccountConnectionString');
exports.DatabaseAccountListConnectionStringsResult = require('./databaseAccountListConnectionStringsResult');
exports.DatabaseAccountRegenerateKeyParameters = require('./databaseAccountRegenerateKeyParameters');
exports.SqlDatabaseResource = require('./sqlDatabaseResource');
exports.SqlDatabaseCreateUpdateParameters = require('./sqlDatabaseCreateUpdateParameters');
exports.ContainerResource = require('./containerResource');
exports.ContainerCreateUpdateParameters = require('./containerCreateUpdateParameters');
exports.MongoDatabaseResource = require('./mongoDatabaseResource');
exports.MongoDatabaseCreateUpdateParameters = require('./mongoDatabaseCreateUpdateParameters');
exports.MongoIndexKeys = require('./mongoIndexKeys');
exports.MongoIndexOptions = require('./mongoIndexOptions');
exports.MongoIndex = require('./mongoIndex');
exports.MongoCollectionResource = require('./mongoCollectionResource');
exports.MongoCollectionCreateUpdateParameters = require('./mongoCollectionCreateUpdateParameters');
exports.TableResource = require('./tableResource');
exports.TableCreateUpdateParameters = require('./tableCreateUpdateParameters');
exports.CassandraKeyspaceResource = require('./cassandraKeyspaceResource');
exports.CassandraKeyspaceCreateUpdateParameters = require('./cassandraKeyspaceCreateUpdateParameters');
exports.Column = require('./column');
exports.CassandraPartitionKey = require('./cassandraPartitionKey');
exports.ClusterKey = require('./clusterKey');
exports.CassandraSchema = require('./cassandraSchema');
exports.CassandraTableResource = require('./cassandraTableResource');
exports.CassandraTableCreateUpdateParameters = require('./cassandraTableCreateUpdateParameters');
exports.GremlinDatabaseResource = require('./gremlinDatabaseResource');
exports.GremlinDatabaseCreateUpdateParameters = require('./gremlinDatabaseCreateUpdateParameters');
exports.OperationDisplay = require('./operationDisplay');
exports.Operation = require('./operation');
exports.MetricName = require('./metricName');
exports.Usage = require('./usage');
exports.PartitionUsage = require('./partitionUsage');
exports.MetricAvailability = require('./metricAvailability');
exports.MetricDefinition = require('./metricDefinition');
exports.MetricValue = require('./metricValue');
exports.Metric = require('./metric');
exports.PercentileMetricValue = require('./percentileMetricValue');
exports.PercentileMetric = require('./percentileMetric');
exports.PartitionMetric = require('./partitionMetric');
exports.DatabaseAccountsListResult = require('./databaseAccountsListResult');
exports.MetricListResult = require('./metricListResult');
exports.UsagesResult = require('./usagesResult');
exports.MetricDefinitionsListResult = require('./metricDefinitionsListResult');
exports.SqlDatabaseListResult = require('./sqlDatabaseListResult');
exports.ContainerListResult = require('./containerListResult');
exports.MongoDatabaseListResult = require('./mongoDatabaseListResult');
exports.MongoCollectionListResult = require('./mongoCollectionListResult');
exports.TableListResult = require('./tableListResult');
exports.CassandraKeyspaceListResult = require('./cassandraKeyspaceListResult');
exports.CassandraTableListResult = require('./cassandraTableListResult');
exports.GremlinDatabaseListResult = require('./gremlinDatabaseListResult');
exports.OperationListResult = require('./operationListResult');
exports.PercentileMetricListResult = require('./percentileMetricListResult');
exports.PartitionMetricListResult = require('./partitionMetricListResult');
exports.PartitionUsagesResult = require('./partitionUsagesResult');
