/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Cosmos DB Mongo collection index options
 *
 */
class MongoIndexOptions {
  /**
   * Create a MongoIndexOptions.
   * @property {number} [expireAfterSeconds] Expire after seconds
   * @property {boolean} [unique] Is unique or not
   */
  constructor() {
  }

  /**
   * Defines the metadata of MongoIndexOptions
   *
   * @returns {object} metadata of MongoIndexOptions
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'MongoIndexOptions',
      type: {
        name: 'Composite',
        className: 'MongoIndexOptions',
        modelProperties: {
          expireAfterSeconds: {
            required: false,
            serializedName: 'expireAfterSeconds',
            type: {
              name: 'Number'
            }
          },
          unique: {
            required: false,
            serializedName: 'unique',
            type: {
              name: 'Boolean'
            }
          }
        }
      }
    };
  }
}

module.exports = MongoIndexOptions;
