/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * An Azure Cosmos DB Mongo database.
 *
 * @extends models['Resource']
 */
class MongoDatabase extends models['Resource'] {
  /**
   * Create a MongoDatabase.
   * @property {string} mongoDatabaseId Name of the Cosmos DB Mongo database
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of MongoDatabase
   *
   * @returns {object} metadata of MongoDatabase
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'MongoDatabase',
      type: {
        name: 'Composite',
        className: 'MongoDatabase',
        modelProperties: {
          id: {
            required: false,
            readOnly: true,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            readOnly: true,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            readOnly: true,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          location: {
            required: false,
            serializedName: 'location',
            type: {
              name: 'String'
            }
          },
          tags: {
            required: false,
            serializedName: 'tags',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          mongoDatabaseId: {
            required: true,
            serializedName: 'properties.id',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = MongoDatabase;
