/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * An Azure Cosmos DB Mongo collection.
 *
 * @extends models['Resource']
 */
class MongoCollection extends models['Resource'] {
  /**
   * Create a MongoCollection.
   * @property {string} mongoCollectionId Name of the Cosmos DB Mongo
   * collection
   * @property {object} [shardKey] A key-value pair of shard keys to be applied
   * for the request.
   * @property {array} [indexes] List of index keys
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of MongoCollection
   *
   * @returns {object} metadata of MongoCollection
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'MongoCollection',
      type: {
        name: 'Composite',
        className: 'MongoCollection',
        modelProperties: {
          id: {
            required: false,
            readOnly: true,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            readOnly: true,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            readOnly: true,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          location: {
            required: false,
            serializedName: 'location',
            type: {
              name: 'String'
            }
          },
          tags: {
            required: false,
            serializedName: 'tags',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          mongoCollectionId: {
            required: true,
            serializedName: 'properties.id',
            type: {
              name: 'String'
            }
          },
          shardKey: {
            required: false,
            serializedName: 'properties.shardKey',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          indexes: {
            required: false,
            serializedName: 'properties.indexes',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'MongoIndexElementType',
                  type: {
                    name: 'Composite',
                    className: 'MongoIndex'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = MongoCollection;
