/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Cosmos DB Mongo collection resource object
 *
 */
class MongoCollectionResource {
  /**
   * Create a MongoCollectionResource.
   * @property {string} id Name of the Cosmos DB Mongo collection
   * @property {object} [shardKey] A key-value pair of shard keys to be applied
   * for the request.
   * @property {array} [indexes] List of index keys
   */
  constructor() {
  }

  /**
   * Defines the metadata of MongoCollectionResource
   *
   * @returns {object} metadata of MongoCollectionResource
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'MongoCollectionResource',
      type: {
        name: 'Composite',
        className: 'MongoCollectionResource',
        modelProperties: {
          id: {
            required: true,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          shardKey: {
            required: false,
            serializedName: 'shardKey',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          indexes: {
            required: false,
            serializedName: 'indexes',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'MongoIndexElementType',
                  type: {
                    name: 'Composite',
                    className: 'MongoIndex'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = MongoCollectionResource;
