/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * An Azure Cosmos DB container.
 *
 * @extends models['Resource']
 */
class SqlContainer extends models['Resource'] {
  /**
   * Create a SqlContainer.
   * @property {string} sqlContainerId Name of the Cosmos DB SQL container
   * @property {object} [indexingPolicy] The configuration of the indexing
   * policy. By default, the indexing is automatic for all document paths
   * within the container
   * @property {boolean} [indexingPolicy.automatic] Indicates if the indexing
   * policy is automatic
   * @property {string} [indexingPolicy.indexingMode] Indicates the indexing
   * mode. Possible values include: 'Consistent', 'Lazy', 'None'
   * @property {array} [indexingPolicy.includedPaths] List of paths to include
   * in the indexing
   * @property {array} [indexingPolicy.excludedPaths] List of paths to exclude
   * from indexing
   * @property {object} [partitionKey] The configuration of the partition key
   * to be used for partitioning data into multiple partitions
   * @property {array} [partitionKey.paths] List of paths using which data
   * within the container can be partitioned
   * @property {string} [partitionKey.kind] Indicates the kind of algorithm
   * used for partitioning. Possible values include: 'Hash', 'Range'
   * @property {number} [defaultTtl] Default time to live
   * @property {object} [uniqueKeyPolicy] The unique key policy configuration
   * for specifying uniqueness constraints on documents in the collection in
   * the Azure Cosmos DB service.
   * @property {array} [uniqueKeyPolicy.uniqueKeys] List of unique keys on that
   * enforces uniqueness constraint on documents in the collection in the Azure
   * Cosmos DB service.
   * @property {object} [conflictResolutionPolicy] The conflict resolution
   * policy for the container.
   * @property {string} [conflictResolutionPolicy.mode] Indicates the conflict
   * resolution mode. Possible values include: 'LastWriterWins', 'Custom'
   * @property {string} [conflictResolutionPolicy.conflictResolutionPath] The
   * conflict resolution path in the case of LastWriterWins mode.
   * @property {string} [conflictResolutionPolicy.conflictResolutionProcedure]
   * The procedure to resolve conflicts in the case of custom mode.
   * @property {string} [_rid] A system generated property. A unique
   * identifier.
   * @property {object} [_ts] A system generated property that denotes the last
   * updated timestamp of the resource.
   * @property {string} [_etag] A system generated property representing the
   * resource etag required for optimistic concurrency control.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of SqlContainer
   *
   * @returns {object} metadata of SqlContainer
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'SqlContainer',
      type: {
        name: 'Composite',
        className: 'SqlContainer',
        modelProperties: {
          id: {
            required: false,
            readOnly: true,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            readOnly: true,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          type: {
            required: false,
            readOnly: true,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          },
          location: {
            required: false,
            serializedName: 'location',
            type: {
              name: 'String'
            }
          },
          tags: {
            required: false,
            serializedName: 'tags',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          sqlContainerId: {
            required: true,
            serializedName: 'properties.id',
            type: {
              name: 'String'
            }
          },
          indexingPolicy: {
            required: false,
            serializedName: 'properties.indexingPolicy',
            type: {
              name: 'Composite',
              className: 'IndexingPolicy'
            }
          },
          partitionKey: {
            required: false,
            serializedName: 'properties.partitionKey',
            type: {
              name: 'Composite',
              className: 'ContainerPartitionKey'
            }
          },
          defaultTtl: {
            required: false,
            serializedName: 'properties.defaultTtl',
            type: {
              name: 'Number'
            }
          },
          uniqueKeyPolicy: {
            required: false,
            serializedName: 'properties.uniqueKeyPolicy',
            type: {
              name: 'Composite',
              className: 'UniqueKeyPolicy'
            }
          },
          conflictResolutionPolicy: {
            required: false,
            serializedName: 'properties.conflictResolutionPolicy',
            type: {
              name: 'Composite',
              className: 'ConflictResolutionPolicy'
            }
          },
          _rid: {
            required: false,
            serializedName: 'properties._rid',
            type: {
              name: 'String'
            }
          },
          _ts: {
            required: false,
            serializedName: 'properties._ts',
            type: {
              name: 'Object'
            }
          },
          _etag: {
            required: false,
            serializedName: 'properties._etag',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = SqlContainer;
