/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Cosmos DB table id object
 *
 */
class TableResource {
  /**
   * Create a TableResource.
   * @property {string} id Name of the Cosmos DB table
   */
  constructor() {
  }

  /**
   * Defines the metadata of TableResource
   *
   * @returns {object} metadata of TableResource
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'TableResource',
      type: {
        name: 'Composite',
        className: 'TableResource',
        modelProperties: {
          id: {
            required: true,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = TableResource;
