/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The unique key policy configuration for specifying uniqueness constraints on
 * documents in the collection in the Azure Cosmos DB service.
 *
 */
class UniqueKeyPolicy {
  /**
   * Create a UniqueKeyPolicy.
   * @property {array} [uniqueKeys] List of unique keys on that enforces
   * uniqueness constraint on documents in the collection in the Azure Cosmos
   * DB service.
   */
  constructor() {
  }

  /**
   * Defines the metadata of UniqueKeyPolicy
   *
   * @returns {object} metadata of UniqueKeyPolicy
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'UniqueKeyPolicy',
      type: {
        name: 'Composite',
        className: 'UniqueKeyPolicy',
        modelProperties: {
          uniqueKeys: {
            required: false,
            serializedName: 'uniqueKeys',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'UniqueKeyElementType',
                  type: {
                    name: 'Composite',
                    className: 'UniqueKey'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = UniqueKeyPolicy;
